import type { ArtistPreview } from '@/features/lineup/types';

// Generated by scripts/update-artist-listening-data.mjs
// Snapshot: 2026-03-14T14:45:50.989Z
export const ARTIST_PREVIEWS: Record<number, ArtistPreview> = {
  1: {
    songs: [
      {
        title: 'Asi Soy Yo',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/a7/6e/d4/a76ed4f0-3689-0108-2beb-c43fd50abe5c/mzaf_4110829861243530862.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/asi-yo-soy/322039048?i=322039455&uo=4',
          spotify: 'https://open.spotify.com/search/Zaturno%20Asi%20Soy%20Yo',
          youtube:
            'https://www.youtube.com/results?search_query=Zaturno%20Asi%20Soy%20Yo',
        },
      },
      {
        title: 'Lautaro',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/53/ee/24/53ee245b-634a-169f-0f36-13cf86cb1cae/mzaf_4970568945064327399.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/lautaro/1268711585?i=1268712927&uo=4',
          spotify: 'https://open.spotify.com/search/Zaturno%20Lautaro',
          youtube: 'https://www.youtube.com/results?search_query=Zaturno%20Lautaro',
        },
      },
      {
        title: 'Letales (feat. Zaturno)',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/Zaturno%20Letales%20(feat.%20Zaturno)',
          youtube:
            'https://www.youtube.com/results?search_query=Zaturno%20Letales%20(feat.%20Zaturno)',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/zaturno/322039158?uo=4',
      spotify: 'https://open.spotify.com/search/Zaturno',
      youtube: 'https://www.youtube.com/results?search_query=Zaturno',
    },
    styleDescription:
      'Set de hip hop / rap chileno con energía en alza, coros fáciles y un clima ideal para ver en vivo a Zaturno.',
    verdict:
      'Si conectas con hip hop / rap chileno, este show es una parada fuerte de la jornada.',
  },
  2: {
    songs: [
      {
        title: 'Domingo de ramos',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/41/18/6f/41186f35-262b-68f4-f2e3-237009379cbb/mzaf_8490179389649102943.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/domingo-de-ramos/1842902072?i=1842902075&uo=4',
          spotify: 'https://open.spotify.com/search/Candelabro%20Domingo%20de%20ramos',
          youtube:
            'https://www.youtube.com/results?search_query=Candelabro%20Domingo%20de%20ramos',
        },
      },
      {
        title: 'Prisión de carne',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/9f/3f/8a/9f3f8a77-4d9b-6b9f-37ff-b395bb0c8233/mzaf_10671297754502004403.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/prisi%C3%B3n-de-carne/1842902072?i=1842902080&uo=4',
          spotify:
            'https://open.spotify.com/search/Candelabro%20Prisi%C3%B3n%20de%20carne',
          youtube:
            'https://www.youtube.com/results?search_query=Candelabro%20Prisi%C3%B3n%20de%20carne',
        },
      },
      {
        title: 'Pecado',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/27/b1/79/27b1797b-3018-7386-64c8-9723f0b8ba41/mzaf_8151309272337852009.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/pecado/1842902072?i=1842902634&uo=4',
          spotify: 'https://open.spotify.com/search/Candelabro%20Pecado',
          youtube: 'https://www.youtube.com/results?search_query=Candelabro%20Pecado',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/candelabro/1723158320?uo=4',
      spotify: 'https://open.spotify.com/search/Candelabro',
      youtube: 'https://www.youtube.com/results?search_query=Candelabro',
    },
    styleDescription:
      'Set de indie rock / rock alternativo con energía en alza, coros fáciles y un clima ideal para ver en vivo a Candelabro.',
    verdict:
      'Si conectas con indie rock / rock alternativo, este show es una parada fuerte de la jornada.',
  },
  3: {
    songs: [
      {
        title: 'End of Beginning',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/6e/df/af/6edfaf58-f901-e9b5-840b-9ac9e37f34b7/mzaf_8465065510938624101.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/end-of-beginning/1632447652?i=1632448108&uo=4',
          spotify: 'https://open.spotify.com/search/Djo%20End%20of%20Beginning',
          youtube:
            'https://www.youtube.com/results?search_query=Djo%20End%20of%20Beginning',
        },
      },
      {
        title: 'Delete Ya',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/7f/a4/7e/7fa47e41-b8be-ed0f-8316-136c31c66d09/mzaf_13728700389116458412.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/delete-ya/1791184860?i=1791184871&uo=4',
          spotify: 'https://open.spotify.com/search/Djo%20Delete%20Ya',
          youtube: 'https://www.youtube.com/results?search_query=Djo%20Delete%20Ya',
        },
      },
      {
        title: 'Basic Being Basic',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/2d/6e/5b/2d6e5bd0-7e8b-98a4-2efd-7a1a458b18e6/mzaf_56754998493673707.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/basic-being-basic/1791184860?i=1791184865&uo=4',
          spotify: 'https://open.spotify.com/search/Djo%20Basic%20Being%20Basic',
          youtube:
            'https://www.youtube.com/results?search_query=Djo%20Basic%20Being%20Basic',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/djo/1473178582?uo=4',
      spotify: 'https://open.spotify.com/search/Djo',
      youtube: 'https://www.youtube.com/results?search_query=Djo',
    },
    styleDescription:
      'Set de indie rock / pop psicodélico con energía en alza, coros fáciles y un clima ideal para ver en vivo a Djo.',
    verdict:
      'Si conectas con indie rock / pop psicodélico, este show es una parada fuerte de la jornada.',
  },
  4: {
    songs: [
      {
        title: 'BIRDS',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/15/aa/94/15aa94d1-9a61-a49e-d150-77be3fe62b88/mzaf_7075406671259860362.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/birds/1805820903?i=1805821732&uo=4',
          spotify: 'https://open.spotify.com/search/Turnstile%20BIRDS',
          youtube: 'https://www.youtube.com/results?search_query=Turnstile%20BIRDS',
        },
      },
      {
        title: 'NEVER ENOUGH',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/d3/62/d1/d362d1e9-6fc6-5dbf-f212-4e64b8d44295/mzaf_13612974613437935378.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/never-enough/1805820903?i=1805820909&uo=4',
          spotify: 'https://open.spotify.com/search/Turnstile%20NEVER%20ENOUGH',
          youtube:
            'https://www.youtube.com/results?search_query=Turnstile%20NEVER%20ENOUGH',
        },
      },
      {
        title: 'BLACKOUT',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/55/72/96/55729631-b8bb-9bb4-eed1-2ef01d77768d/mzaf_11256081667780001792.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/blackout/1576430192?i=1576430194&uo=4',
          spotify: 'https://open.spotify.com/search/Turnstile%20BLACKOUT',
          youtube: 'https://www.youtube.com/results?search_query=Turnstile%20BLACKOUT',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/turnstile/4472006?uo=4',
      spotify: 'https://open.spotify.com/search/Turnstile',
      youtube: 'https://www.youtube.com/results?search_query=Turnstile',
    },
    styleDescription:
      'Set de hardcore punk / rock alternativo con energía en alza, coros fáciles y un clima ideal para ver en vivo a Turnstile.',
    verdict:
      'Si conectas con hardcore punk / rock alternativo, este show es una parada fuerte de la jornada.',
  },
  5: {
    songs: [
      {
        title: 'See You Again (feat. Kali Uchis)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/b6/2d/c3/b62dc335-20fa-d730-d09a-cf1d5cdeb6f1/mzaf_12522863608799747750.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/see-you-again/1692204815?i=1692204822&uo=4',
          spotify:
            'https://open.spotify.com/search/Tyler%2C%20The%20Creator%20See%20You%20Again%20(feat.%20Kali%20Uchis)',
          youtube:
            'https://www.youtube.com/results?search_query=Tyler%2C%20The%20Creator%20See%20You%20Again%20(feat.%20Kali%20Uchis)',
        },
      },
      {
        title: 'Like Him (feat. Lola Young)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/f8/16/31/f81631fe-84f4-a48e-518e-4e11e99339c4/mzaf_13519420484368287837.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/like-him-feat-lola-young/1789446415?i=1789446436&uo=4',
          spotify:
            'https://open.spotify.com/search/Tyler%2C%20The%20Creator%20Like%20Him%20(feat.%20Lola%20Young)',
          youtube:
            'https://www.youtube.com/results?search_query=Tyler%2C%20The%20Creator%20Like%20Him%20(feat.%20Lola%20Young)',
        },
      },
      {
        title: 'Sugar On My Tongue',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/f0/71/c1/f071c182-fa6c-846b-0bdc-f52e1b9c37c6/mzaf_11614860346974476363.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/sugar-on-my-tongue/1828766736?i=1828767309&uo=4',
          spotify:
            'https://open.spotify.com/search/Tyler%2C%20The%20Creator%20Sugar%20On%20My%20Tongue',
          youtube:
            'https://www.youtube.com/results?search_query=Tyler%2C%20The%20Creator%20Sugar%20On%20My%20Tongue',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/tyler-the-creator/420368335?uo=4',
      spotify: 'https://open.spotify.com/search/Tyler%2C%20The%20Creator',
      youtube: 'https://www.youtube.com/results?search_query=Tyler%2C%20The%20Creator',
    },
    styleDescription:
      'Set de hip hop / rap alternativo con energía en alza, coros fáciles y un clima ideal para ver en vivo a Tyler, The Creator.',
    verdict:
      'Si conectas con hip hop / rap alternativo, este show es una parada fuerte de la jornada.',
  },
  6: {
    songs: [
      {
        title: 'Ay Mami! (feat. Pablo Rojas, DJ Acres)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/de/eb/15/deeb1579-c605-1763-996d-3d28d0547758/mzaf_14274957160593558071.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/ay-mami-feat-pablo-rojas-dj-acres/1853132408?i=1853132410&uo=4',
          spotify:
            'https://open.spotify.com/search/Astronautiko%20Ay%20Mami!%20(feat.%20Pablo%20Rojas%2C%20DJ%20Acres)',
          youtube:
            'https://www.youtube.com/results?search_query=Astronautiko%20Ay%20Mami!%20(feat.%20Pablo%20Rojas%2C%20DJ%20Acres)',
        },
      },
      {
        title: 'Resistiendo',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/ad/18/c8/ad18c84f-3f70-65c7-b8d5-04b9e0139ce4/mzaf_15482297139198689228.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/resistiendo/1713389515?i=1713389517&uo=4',
          spotify: 'https://open.spotify.com/search/Astronautiko%20Resistiendo',
          youtube:
            'https://www.youtube.com/results?search_query=Astronautiko%20Resistiendo',
        },
      },
      {
        title: 'Bajo la Luna',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview112/v4/ec/b3/26/ecb326a2-953d-c52b-43e1-d317d0ac6459/mzaf_18254880159965063202.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/bajo-la-luna/1634137279?i=1634137280&uo=4',
          spotify: 'https://open.spotify.com/search/Astronautiko%20Bajo%20la%20Luna',
          youtube:
            'https://www.youtube.com/results?search_query=Astronautiko%20Bajo%20la%20Luna',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/astronautiko/1512393096?uo=4',
      spotify: 'https://open.spotify.com/search/Astronautiko',
      youtube: 'https://www.youtube.com/results?search_query=Astronautiko',
    },
    styleDescription:
      'Set de folk urbano / rap con energía en alza, coros fáciles y un clima ideal para ver en vivo a Astronautiko.',
    verdict:
      'Si conectas con folk urbano / rap, este show es una parada fuerte de la jornada.',
  },
  7: {
    songs: [
      {
        title: 'El Bolero',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/71/8c/10/718c1013-3cc8-021c-cb1e-7883fe3853b7/mzaf_9169124794418302292.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/el-bolero/1653867075?i=1653867827&uo=4',
          spotify: 'https://open.spotify.com/search/Yami%20Safdie%20El%20Bolero',
          youtube:
            'https://www.youtube.com/results?search_query=Yami%20Safdie%20El%20Bolero',
        },
      },
      {
        title: 'En Otra Vida',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/1b/fc/55/1bfc55c2-0be3-5c02-a538-f8aa3d22ac97/mzaf_1026494978474626297.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/en-otra-vida/1771451032?i=1771451037&uo=4',
          spotify: 'https://open.spotify.com/search/Yami%20Safdie%20En%20Otra%20Vida',
          youtube:
            'https://www.youtube.com/results?search_query=Yami%20Safdie%20En%20Otra%20Vida',
        },
      },
      {
        title: 'CARENCIAS DE CORDURA',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/62/0d/29/620d2968-ade8-87af-5c2c-673464843fef/mzaf_12287406220477442118.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/carencias-de-cordura/1724126218?i=1724126230&uo=4',
          spotify:
            'https://open.spotify.com/search/Yami%20Safdie%20CARENCIAS%20DE%20CORDURA',
          youtube:
            'https://www.youtube.com/results?search_query=Yami%20Safdie%20CARENCIAS%20DE%20CORDURA',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/yami-safdie/1291593068?uo=4',
      spotify: 'https://open.spotify.com/search/Yami%20Safdie',
      youtube: 'https://www.youtube.com/results?search_query=Yami%20Safdie',
    },
    styleDescription:
      'Set de pop / indie pop con energía en alza, coros fáciles y un clima ideal para ver en vivo a Yami Safdie.',
    verdict:
      'Si conectas con pop / indie pop, este show es una parada fuerte de la jornada.',
  },
  8: {
    songs: [
      {
        title: 'Linger - SiriusXM Session',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/81/70/72/8170727e-5c4e-5fcc-427b-410b4b9441c6/mzaf_7008226677286998422.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/linger-siriusxm-session/1747990430?i=1747990434&uo=4',
          spotify:
            'https://open.spotify.com/search/Royel%20Otis%20Linger%20-%20SiriusXM%20Session',
          youtube:
            'https://www.youtube.com/results?search_query=Royel%20Otis%20Linger%20-%20SiriusXM%20Session',
        },
      },
      {
        title: 'Oysters In My Pocket',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/16/74/fd/1674fd07-1169-0195-ebe7-f59dff039022/mzaf_11077054326676261432.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/oysters-in-my-pocket/1610782067?i=1610782071&uo=4',
          spotify:
            'https://open.spotify.com/search/Royel%20Otis%20Oysters%20In%20My%20Pocket',
          youtube:
            'https://www.youtube.com/results?search_query=Royel%20Otis%20Oysters%20In%20My%20Pocket',
        },
      },
      {
        title: 'who’s your boyfriend',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/fe/ee/24/feee244e-b2f7-d488-8b00-e6c69ef2b8d7/mzaf_570126664547596035.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/whos-your-boyfriend/1831345087?i=1831345173&uo=4',
          spotify:
            'https://open.spotify.com/search/Royel%20Otis%20who%E2%80%99s%20your%20boyfriend',
          youtube:
            'https://www.youtube.com/results?search_query=Royel%20Otis%20who%E2%80%99s%20your%20boyfriend',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/royel-otis/1537647213?uo=4',
      spotify: 'https://open.spotify.com/search/Royel%20Otis',
      youtube: 'https://www.youtube.com/results?search_query=Royel%20Otis',
    },
    styleDescription:
      'Set de indie pop / indie rock con energía en alza, coros fáciles y un clima ideal para ver en vivo a Royel Otis.',
    verdict:
      'Si conectas con indie pop / indie rock, este show es una parada fuerte de la jornada.',
  },
  9: {
    songs: [
      {
        title: 'Gabriela',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/e1/02/e6/e102e60f-e529-c7af-0a99-afadea88e0cf/mzaf_4063426124739522501.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/gabriela/1811464270?i=1811464273&uo=4',
          spotify: 'https://open.spotify.com/search/KATSEYE%20Gabriela',
          youtube: 'https://www.youtube.com/results?search_query=KATSEYE%20Gabriela',
        },
      },
      {
        title: 'Gnarly',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/62/c4/d8/62c4d84b-eefb-db63-448d-1bb6ea6b84e8/mzaf_5197802835054503712.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/gnarly/1809020555?i=1809020562&uo=4',
          spotify: 'https://open.spotify.com/search/KATSEYE%20Gnarly',
          youtube: 'https://www.youtube.com/results?search_query=KATSEYE%20Gnarly',
        },
      },
      {
        title: 'Touch',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/9f/1d/86/9f1d8632-0842-ba50-107d-1f3bc5b7b362/mzaf_6667750882234216216.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/touch/1753359526?i=1753359801&uo=4',
          spotify: 'https://open.spotify.com/search/KATSEYE%20Touch',
          youtube: 'https://www.youtube.com/results?search_query=KATSEYE%20Touch',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/katseye/1754284416?uo=4',
      spotify: 'https://open.spotify.com/search/KATSEYE',
      youtube: 'https://www.youtube.com/results?search_query=KATSEYE',
    },
    styleDescription:
      'Set de pop con energía en alza, coros fáciles y un clima ideal para ver en vivo a KATSEYE.',
    verdict: 'Si conectas con pop, este show es una parada fuerte de la jornada.',
  },
  10: {
    songs: [
      {
        title: 'Ribs',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/06/37/d8/0637d80c-bc43-63fa-6bdb-ccda8412cd8e/mzaf_6914525951591873635.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/ribs/1440818584?i=1440818666&uo=4',
          spotify: 'https://open.spotify.com/search/Lorde%20Ribs',
          youtube: 'https://www.youtube.com/results?search_query=Lorde%20Ribs',
        },
      },
      {
        title: 'Team',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/47/e9/27/47e927ce-bf78-6a94-6a68-9ac76c69d414/mzaf_2350071649770408732.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/team/1440818584?i=1440818672&uo=4',
          spotify: 'https://open.spotify.com/search/Lorde%20Team',
          youtube: 'https://www.youtube.com/results?search_query=Lorde%20Team',
        },
      },
      {
        title: 'Royals',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/36/b5/16/36b5162c-cf3e-d8ef-eb31-5e14f2e5f616/mzaf_5021657451820310202.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/royals/1440818584?i=1440818664&uo=4',
          spotify: 'https://open.spotify.com/search/Lorde%20Royals',
          youtube: 'https://www.youtube.com/results?search_query=Lorde%20Royals',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/lorde/602767352?uo=4',
      spotify: 'https://open.spotify.com/search/Lorde',
      youtube: 'https://www.youtube.com/results?search_query=Lorde',
    },
    styleDescription:
      'Set de indie pop / electropop con energía en alza, coros fáciles y un clima ideal para ver en vivo a Lorde.',
    verdict:
      'Si conectas con indie pop / electropop, este show es una parada fuerte de la jornada.',
  },
  11: {
    songs: [
      {
        title: 'Llueve Sobre La Ciudad',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/09/28/58/09285865-246f-4472-1d08-52fa13deb1e1/mzaf_12998828905205874876.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/llueve-sobre-la-ciudad/1776311914?i=1776311924&uo=4',
          spotify:
            'https://open.spotify.com/search/Los%20Bunkers%20Llueve%20Sobre%20La%20Ciudad',
          youtube:
            'https://www.youtube.com/results?search_query=Los%20Bunkers%20Llueve%20Sobre%20La%20Ciudad',
        },
      },
      {
        title: 'Bailando Solo',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/87/81/be/8781be9d-70f5-a91d-5af4-fcd0735010d6/mzaf_5238754567565665090.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/bailando-solo/1398637829?i=1398638466&uo=4',
          spotify: 'https://open.spotify.com/search/Los%20Bunkers%20Bailando%20Solo',
          youtube:
            'https://www.youtube.com/results?search_query=Los%20Bunkers%20Bailando%20Solo',
        },
      },
      {
        title: 'Ven Aquí',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/bb/6a/48/bb6a482f-b078-e60b-f4c0-6dcd190605a4/mzaf_7931131929886002984.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/ven-aqu%C3%AD/1776311914?i=1776311920&uo=4',
          spotify: 'https://open.spotify.com/search/Los%20Bunkers%20Ven%20Aqu%C3%AD',
          youtube:
            'https://www.youtube.com/results?search_query=Los%20Bunkers%20Ven%20Aqu%C3%AD',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/los-bunkers/41216290?uo=4',
      spotify: 'https://open.spotify.com/search/Los%20Bunkers',
      youtube: 'https://www.youtube.com/results?search_query=Los%20Bunkers',
    },
    styleDescription:
      'Set de rock alternativo / pop rock con energía en alza, coros fáciles y un clima ideal para ver en vivo a Los Bunkers.',
    verdict:
      'Si conectas con rock alternativo / pop rock, este show es una parada fuerte de la jornada.',
  },
  12: {
    songs: [
      {
        title: 'No sirve sin dolor',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview124/v4/4e/f9/61/4ef9618f-70bb-2b75-d837-331c65ef4e00/mzaf_9045852292007747870.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/no-sirve-sin-dolor/1453760785?i=1453761039&uo=4',
          spotify:
            'https://open.spotify.com/search/Mano%20de%20Obra%20No%20sirve%20sin%20dolor',
          youtube:
            'https://www.youtube.com/results?search_query=Mano%20de%20Obra%20No%20sirve%20sin%20dolor',
        },
      },
      {
        title: 'Fulgor',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/16/01/98/16019890-daec-5bff-992f-e28a09764dcc/mzaf_5889463144928981289.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/fulgor/1880731218?i=1880731219&uo=4',
          spotify: 'https://open.spotify.com/search/Mano%20de%20Obra%20Fulgor',
          youtube:
            'https://www.youtube.com/results?search_query=Mano%20de%20Obra%20Fulgor',
        },
      },
      {
        title: 'Vienen Por Mí',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/fc/72/02/fc720241-2a5b-d778-2923-51aa812f2e7e/mzaf_4282343741155588715.plus.aac.p.m4a',
        links: {
          appleMusic: 'https://music.apple.com/cl/album/gaia/369875050?i=369875121&uo=4',
          spotify:
            'https://open.spotify.com/search/Mano%20de%20Obra%20Vienen%20Por%20M%C3%AD',
          youtube:
            'https://www.youtube.com/results?search_query=Mano%20de%20Obra%20Vienen%20Por%20M%C3%AD',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/mano-de-obra/1453761033?uo=4',
      spotify: 'https://open.spotify.com/search/Mano%20de%20Obra',
      youtube: 'https://www.youtube.com/results?search_query=Mano%20de%20Obra',
    },
    styleDescription:
      'Set de rock con energía en alza, coros fáciles y un clima ideal para ver en vivo a Mano de Obra.',
    verdict: 'Si conectas con rock, este show es una parada fuerte de la jornada.',
  },
  13: {
    songs: [
      {
        title: 'Nuestra señal',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/31/85/76/318576c0-dc77-39bd-794d-fff84b2d21aa/mzaf_1270433514114645054.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/nuestra-se%C3%B1al/1808090555?i=1808091137&uo=4',
          spotify: 'https://open.spotify.com/search/De%20Saloon%20Nuestra%20se%C3%B1al',
          youtube:
            'https://www.youtube.com/results?search_query=De%20Saloon%20Nuestra%20se%C3%B1al',
        },
      },
      {
        title: 'Te Mueres',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/75/8a/28/758a28cd-17b3-ef57-0779-3050ad62c995/mzaf_3122703559731817406.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/te-mueres/1810859606?i=1810859615&uo=4',
          spotify: 'https://open.spotify.com/search/De%20Saloon%20Te%20Mueres',
          youtube:
            'https://www.youtube.com/results?search_query=De%20Saloon%20Te%20Mueres',
        },
      },
      {
        title: 'Déjalo',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/53/cb/6f/53cb6f81-56a1-28d3-048f-a3ef57db37bf/mzaf_1091203733137256382.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/d%C3%A9jalo/1808081881?i=1808082538&uo=4',
          spotify: 'https://open.spotify.com/search/De%20Saloon%20D%C3%A9jalo',
          youtube:
            'https://www.youtube.com/results?search_query=De%20Saloon%20D%C3%A9jalo',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/de-saloon/277140639?uo=4',
      spotify: 'https://open.spotify.com/search/De%20Saloon',
      youtube: 'https://www.youtube.com/results?search_query=De%20Saloon',
    },
    styleDescription:
      'Set de pop rock / rock chileno con energía en alza, coros fáciles y un clima ideal para ver en vivo a De Saloon.',
    verdict:
      'Si conectas con pop rock / rock chileno, este show es una parada fuerte de la jornada.',
  },
  14: {
    songs: [
      {
        title: 'si preguntas por mi',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Judeline%20si%20preguntas%20por%20mi',
          youtube:
            'https://www.youtube.com/results?search_query=Judeline%20si%20preguntas%20por%20mi',
        },
      },
      {
        title: 'Heavenly',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/df/4e/65/df4e6560-38a3-eeba-eccb-b928cddc2fd9/mzaf_3613124490240984874.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/heavenly/1774589372?i=1774590152&uo=4',
          spotify: 'https://open.spotify.com/search/Judeline%20Heavenly',
          youtube: 'https://www.youtube.com/results?search_query=Judeline%20Heavenly',
        },
      },
      {
        title: 'mangata',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/88/71/0e/88710e32-7186-6ad8-180e-edf83d3c4bcf/mzaf_1805062346286526403.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/mangata/1774589372?i=1774589609&uo=4',
          spotify: 'https://open.spotify.com/search/Judeline%20mangata',
          youtube: 'https://www.youtube.com/results?search_query=Judeline%20mangata',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/judeline/1487503245?uo=4',
      spotify: 'https://open.spotify.com/search/Judeline',
      youtube: 'https://www.youtube.com/results?search_query=Judeline',
    },
    styleDescription:
      'Set de indie pop / latin pop con energía en alza, coros fáciles y un clima ideal para ver en vivo a Judeline.',
    verdict:
      'Si conectas con indie pop / latin pop, este show es una parada fuerte de la jornada.',
  },
  15: {
    songs: [
      {
        title: 'So Cold',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/61/4d/77/614d77d3-882c-814e-6eaa-25c45e0af8f5/mzaf_2642987810505072254.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/so-cold/1750274324?i=1750274397&uo=4',
          spotify: 'https://open.spotify.com/search/Balu%20Brigada%20So%20Cold',
          youtube:
            'https://www.youtube.com/results?search_query=Balu%20Brigada%20So%20Cold',
        },
      },
      {
        title: 'Backseat',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/93/2d/78/932d7881-1564-6ba2-dfc7-19b402784e6d/mzaf_9661635533200151923.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/backseat/1815926072?i=1815926074&uo=4',
          spotify: 'https://open.spotify.com/search/Balu%20Brigada%20Backseat',
          youtube:
            'https://www.youtube.com/results?search_query=Balu%20Brigada%20Backseat',
        },
      },
      {
        title: 'Sideways',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/e2/bd/1a/e2bd1a4e-d2e3-29d9-adf0-32145a7a7b09/mzaf_2994190921200097694.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/sideways/1834660784?i=1834660785&uo=4',
          spotify: 'https://open.spotify.com/search/Balu%20Brigada%20Sideways',
          youtube:
            'https://www.youtube.com/results?search_query=Balu%20Brigada%20Sideways',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/balu-brigada/1171521321?uo=4',
      spotify: 'https://open.spotify.com/search/Balu%20Brigada',
      youtube: 'https://www.youtube.com/results?search_query=Balu%20Brigada',
    },
    styleDescription:
      'Set de alt-pop / indie rock con energía en alza, coros fáciles y un clima ideal para ver en vivo a Balu Brigada.',
    verdict:
      'Si conectas con alt-pop / indie rock, este show es una parada fuerte de la jornada.',
  },
  16: {
    songs: [
      {
        title: 'Represent',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/ee/c8/8c/eec88caf-c851-eefd-3974-bac675941f69/mzaf_13399421611328196785.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/represent/726238957?i=726238976&uo=4',
          spotify: 'https://open.spotify.com/search/Orishas%20Represent',
          youtube: 'https://www.youtube.com/results?search_query=Orishas%20Represent',
        },
      },
      {
        title: 'A Lo Cubano',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/3f/b9/3f/3fb93f23-9aec-d3fd-9009-c92e3cd31a90/mzaf_12468288675445753197.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/a-lo-cubano/726238957?i=726239001&uo=4',
          spotify: 'https://open.spotify.com/search/Orishas%20A%20Lo%20Cubano',
          youtube:
            'https://www.youtube.com/results?search_query=Orishas%20A%20Lo%20Cubano',
        },
      },
      {
        title: '537 C U B A',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/b7/d4/76/b7d4761e-8821-5357-46c1-c261def557fa/mzaf_1983546811344994057.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/537-c-u-b-a/726238957?i=726239027&uo=4',
          spotify: 'https://open.spotify.com/search/Orishas%20537%20C%20U%20B%20A',
          youtube:
            'https://www.youtube.com/results?search_query=Orishas%20537%20C%20U%20B%20A',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/orishas/103897?uo=4',
      spotify: 'https://open.spotify.com/search/Orishas',
      youtube: 'https://www.youtube.com/results?search_query=Orishas',
    },
    styleDescription:
      'Set de hip hop cubano con energía en alza, coros fáciles y un clima ideal para ver en vivo a Orishas.',
    verdict:
      'Si conectas con hip hop cubano, este show es una parada fuerte de la jornada.',
  },
  17: {
    songs: [
      {
        title: 'Blanco Bootleg',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/6c/6c/1a/6c6c1acb-0cc0-a139-c3e3-3c3a46e208d4/mzaf_13261356538615436834.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/blanco-bootleg/1692943037?i=1692943039&uo=4',
          spotify: 'https://open.spotify.com/search/Bruno%20Borlone%20Blanco%20Bootleg',
          youtube:
            'https://www.youtube.com/results?search_query=Bruno%20Borlone%20Blanco%20Bootleg',
        },
      },
      {
        title: 'Rebota Bootleg',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/2e/05/0e/2e050eae-80d4-4259-904c-4e522a5c399c/mzaf_15341441980406172413.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/rebota-bootleg/1808796541?i=1808796542&uo=4',
          spotify: 'https://open.spotify.com/search/Bruno%20Borlone%20Rebota%20Bootleg',
          youtube:
            'https://www.youtube.com/results?search_query=Bruno%20Borlone%20Rebota%20Bootleg',
        },
      },
      {
        title: 'Mil Horas',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview112/v4/05/56/6a/05566a67-a350-13ac-01bd-b2c9ebb1bf6a/mzaf_433909434703821084.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/mil-horas/1657350518?i=1657350519&uo=4',
          spotify: 'https://open.spotify.com/search/Bruno%20Borlone%20Mil%20Horas',
          youtube:
            'https://www.youtube.com/results?search_query=Bruno%20Borlone%20Mil%20Horas',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/bruno-borlone/934274543?uo=4',
      spotify: 'https://open.spotify.com/search/Bruno%20Borlone',
      youtube: 'https://www.youtube.com/results?search_query=Bruno%20Borlone',
    },
    styleDescription:
      'Set de electrónica / dj set con energía en alza, coros fáciles y un clima ideal para ver en vivo a Bruno Borlone.',
    verdict:
      'Si conectas con electrónica / dj set, este show es una parada fuerte de la jornada.',
  },
  18: {
    songs: [
      {
        title: 'Pal Casino',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Marlon%20Breeze%20Pal%20Casino',
          youtube:
            'https://www.youtube.com/results?search_query=Marlon%20Breeze%20Pal%20Casino',
        },
      },
      {
        title: 'Shisholina',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/47/73/29/47732920-e023-c130-1245-4b4c7997c0f8/mzaf_2804362988879067259.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/shisholina-rmx/1860144724?i=1860144725&uo=4',
          spotify: 'https://open.spotify.com/search/Marlon%20Breeze%20Shisholina',
          youtube:
            'https://www.youtube.com/results?search_query=Marlon%20Breeze%20Shisholina',
        },
      },
      {
        title: 'Co Shina',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/e6/7c/92/e67c92b6-a4ac-f889-086d-51834f24bbdb/mzaf_859054720014130878.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/co-shina-rmx/1860144724?i=1860144727&uo=4',
          spotify: 'https://open.spotify.com/search/Marlon%20Breeze%20Co%20Shina',
          youtube:
            'https://www.youtube.com/results?search_query=Marlon%20Breeze%20Co%20Shina',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/marlon-breeze/1017950967?uo=4',
      spotify: 'https://open.spotify.com/search/Marlon%20Breeze',
      youtube: 'https://www.youtube.com/results?search_query=Marlon%20Breeze',
    },
    styleDescription:
      'Set de trap / hip hop con energía en alza, coros fáciles y un clima ideal para ver en vivo a Marlon Breeze.',
    verdict:
      'Si conectas con trap / hip hop, este show es una parada fuerte de la jornada.',
  },
  19: {
    songs: [
      {
        title: 'La Estrella',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Aura%20Bae%20La%20Estrella',
          youtube:
            'https://www.youtube.com/results?search_query=Aura%20Bae%20La%20Estrella',
        },
      },
      {
        title: '777',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Aura%20Bae%20777',
          youtube: 'https://www.youtube.com/results?search_query=Aura%20Bae%20777',
        },
      },
      {
        title: 'Palomita',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/4d/c8/2c/4dc82cb1-bafd-31a3-a5cc-e28c906940b0/mzaf_1404078024869770544.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/palomita/1858989070?i=1858989076&uo=4',
          spotify: 'https://open.spotify.com/search/Aura%20Bae%20Palomita',
          youtube: 'https://www.youtube.com/results?search_query=Aura%20Bae%20Palomita',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/aura-bae/1572198218?uo=4',
      spotify: 'https://open.spotify.com/search/Aura%20Bae',
      youtube: 'https://www.youtube.com/results?search_query=Aura%20Bae',
    },
    styleDescription:
      'Set de urbano con energía en alza, coros fáciles y un clima ideal para ver en vivo a Aura Bae.',
    verdict: 'Si conectas con urbano, este show es una parada fuerte de la jornada.',
  },
  20: {
    songs: [
      {
        title: 'TODO KE VER',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Katteyes%20TODO%20KE%20VER',
          youtube:
            'https://www.youtube.com/results?search_query=Katteyes%20TODO%20KE%20VER',
        },
      },
      {
        title: 'ALO',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Katteyes%20ALO',
          youtube: 'https://www.youtube.com/results?search_query=Katteyes%20ALO',
        },
      },
      {
        title: 'Pasajero',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Katteyes%20Pasajero',
          youtube: 'https://www.youtube.com/results?search_query=Katteyes%20Pasajero',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/katteyes/1648818255?uo=4',
      spotify: 'https://open.spotify.com/search/Katteyes',
      youtube: 'https://www.youtube.com/results?search_query=Katteyes',
    },
    styleDescription:
      'Set de electrónica / dance con energía en alza, coros fáciles y un clima ideal para ver en vivo a Katteyes.',
    verdict:
      'Si conectas con electrónica / dance, este show es una parada fuerte de la jornada.',
  },
  21: {
    songs: [
      {
        title: 'Peligrosa (Version Aerobica)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/e6/c9/08/e6c908d2-cf78-d9bd-d053-dcac80d4b3c8/mzaf_10496922550521727302.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/peligrosa-version-aerobica-feat-javiera-mena/1758713191?i=1758713195&uo=4',
          spotify:
            'https://open.spotify.com/search/Aerobica%20Peligrosa%20(Version%20Aerobica)',
          youtube:
            'https://www.youtube.com/results?search_query=Aerobica%20Peligrosa%20(Version%20Aerobica)',
        },
      },
      {
        title: 'Party Time (feat. Locomia)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/16/0e/71/160e7120-3323-11be-bb6f-43d860249588/mzaf_779703411748222063.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/party-time-feat-locomia/1762924774?i=1762924776&uo=4',
          spotify:
            'https://open.spotify.com/search/Aerobica%20Party%20Time%20(feat.%20Locomia)',
          youtube:
            'https://www.youtube.com/results?search_query=Aerobica%20Party%20Time%20(feat.%20Locomia)',
        },
      },
      {
        title: 'Papi',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Aerobica%20Papi',
          youtube: 'https://www.youtube.com/results?search_query=Aerobica%20Papi',
        },
      },
    ],
    artistLinks: {
      appleMusic: null,
      spotify: 'https://open.spotify.com/search/Aerobica',
      youtube: 'https://www.youtube.com/results?search_query=Aerobica',
    },
    styleDescription:
      'Set de house con energía en alza, coros fáciles y un clima ideal para ver en vivo a Aerobica.',
    verdict: 'Si conectas con house, este show es una parada fuerte de la jornada.',
  },
  22: {
    songs: [
      {
        title: 'flashes',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/R%C3%98Z%20flashes',
          youtube: 'https://www.youtube.com/results?search_query=R%C3%98Z%20flashes',
        },
      },
      {
        title: 'CORA DE HIELO',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/R%C3%98Z%20CORA%20DE%20HIELO',
          youtube:
            'https://www.youtube.com/results?search_query=R%C3%98Z%20CORA%20DE%20HIELO',
        },
      },
      {
        title: 'Apaga la luz',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/R%C3%98Z%20Apaga%20la%20luz',
          youtube:
            'https://www.youtube.com/results?search_query=R%C3%98Z%20Apaga%20la%20luz',
        },
      },
    ],
    artistLinks: {
      appleMusic: null,
      spotify: 'https://open.spotify.com/search/R%C3%98Z',
      youtube: 'https://www.youtube.com/results?search_query=R%C3%98Z',
    },
    styleDescription:
      'Set de electrónica con energía en alza, coros fáciles y un clima ideal para ver en vivo a RØZ.',
    verdict: 'Si conectas con electrónica, este show es una parada fuerte de la jornada.',
  },
  23: {
    songs: [
      {
        title: "Midnight is Comin' - Mixed",
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            "https://open.spotify.com/search/%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20Midnight%20is%20Comin'%20-%20Mixed",
          youtube:
            "https://www.youtube.com/results?search_query=%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20Midnight%20is%20Comin'%20-%20Mixed",
        },
      },
      {
        title: 'Kulikitaka - Schranz Edit',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20Kulikitaka%20-%20Schranz%20Edit',
          youtube:
            'https://www.youtube.com/results?search_query=%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20Kulikitaka%20-%20Schranz%20Edit',
        },
      },
      {
        title: 'Kuliki (Schranz)',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20Kuliki%20(Schranz)',
          youtube:
            'https://www.youtube.com/results?search_query=%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20Kuliki%20(Schranz)',
        },
      },
    ],
    artistLinks: {
      appleMusic: null,
      spotify:
        'https://open.spotify.com/search/%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U',
      youtube:
        'https://www.youtube.com/results?search_query=%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U',
    },
    styleDescription:
      'Set de techno experimental con energía en alza, coros fáciles y un clima ideal para ver en vivo a ¥ØU$UK€ ¥UK1MAT$U.',
    verdict:
      'Si conectas con techno experimental, este show es una parada fuerte de la jornada.',
  },
  24: {
    songs: [
      {
        title: '(It Goes Like) Nanana - Edit',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/Peggy%20Gou%20(It%20Goes%20Like)%20Nanana%20-%20Edit',
          youtube:
            'https://www.youtube.com/results?search_query=Peggy%20Gou%20(It%20Goes%20Like)%20Nanana%20-%20Edit',
        },
      },
      {
        title: '(It Goes Like) Nanana',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/Peggy%20Gou%20(It%20Goes%20Like)%20Nanana',
          youtube:
            'https://www.youtube.com/results?search_query=Peggy%20Gou%20(It%20Goes%20Like)%20Nanana',
        },
      },
      {
        title: 'Starry Night - Edit',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/Peggy%20Gou%20Starry%20Night%20-%20Edit',
          youtube:
            'https://www.youtube.com/results?search_query=Peggy%20Gou%20Starry%20Night%20-%20Edit',
        },
      },
    ],
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/peggy-gou/1068912248?uo=4',
      spotify: 'https://open.spotify.com/search/Peggy%20Gou',
      youtube: 'https://www.youtube.com/results?search_query=Peggy%20Gou',
    },
    styleDescription:
      'Set de house / techno con energía en alza, coros fáciles y un clima ideal para ver en vivo a Peggy Gou.',
    verdict:
      'Si conectas con house / techno, este show es una parada fuerte de la jornada.',
  },
  25: {
    songs: [
      {
        title: 'Findesemana',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Fonosida%20Findesemana',
          youtube: 'https://www.youtube.com/results?search_query=Fonosida%20Findesemana',
        },
      },
      {
        title: 'Hagamos Como Si Nada de Esto Hubiera Pasado (Emm Ok)',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/Fonosida%20Hagamos%20Como%20Si%20Nada%20de%20Esto%20Hubiera%20Pasado%20(Emm%20Ok)',
          youtube:
            'https://www.youtube.com/results?search_query=Fonosida%20Hagamos%20Como%20Si%20Nada%20de%20Esto%20Hubiera%20Pasado%20(Emm%20Ok)',
        },
      },
      {
        title: 'Islas',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Fonosida%20Islas',
          youtube: 'https://www.youtube.com/results?search_query=Fonosida%20Islas',
        },
      },
    ],
    artistLinks: {
      appleMusic: null,
      spotify: 'https://open.spotify.com/search/Fonosida',
      youtube: 'https://www.youtube.com/results?search_query=Fonosida',
    },
    styleDescription:
      'Set de indie pop con energía en alza, coros fáciles y un clima ideal para ver en vivo a Fonosida.',
    verdict: 'Si conectas con indie pop, este show es una parada fuerte de la jornada.',
  },
  26: {
    songs: [
      {
        title: 'Disparan (Fill the skies)',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/Como%20Asesinar%20a%20Felipes%20Disparan%20(Fill%20the%20skies)',
          youtube:
            'https://www.youtube.com/results?search_query=Como%20Asesinar%20a%20Felipes%20Disparan%20(Fill%20the%20skies)',
        },
      },
      {
        title: 'La puerta no se abre sola',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/Como%20Asesinar%20a%20Felipes%20La%20puerta%20no%20se%20abre%20sola',
          youtube:
            'https://www.youtube.com/results?search_query=Como%20Asesinar%20a%20Felipes%20La%20puerta%20no%20se%20abre%20sola',
        },
      },
      {
        title: 'Canción de una canción',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/Como%20Asesinar%20a%20Felipes%20Canci%C3%B3n%20de%20una%20canci%C3%B3n',
          youtube:
            'https://www.youtube.com/results?search_query=Como%20Asesinar%20a%20Felipes%20Canci%C3%B3n%20de%20una%20canci%C3%B3n',
        },
      },
    ],
    artistLinks: {
      appleMusic: null,
      spotify: 'https://open.spotify.com/search/Como%20Asesinar%20a%20Felipes',
      youtube:
        'https://www.youtube.com/results?search_query=Como%20Asesinar%20a%20Felipes',
    },
    styleDescription:
      'Set de jazz rap con energía en alza, coros fáciles y un clima ideal para ver en vivo a Como Asesinar a Felipes.',
    verdict: 'Si conectas con jazz rap, este show es una parada fuerte de la jornada.',
  },
  27: {
    songs: [
      {
        title: 'Saico',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Chicarica%20Saico',
          youtube: 'https://www.youtube.com/results?search_query=Chicarica%20Saico',
        },
      },
      {
        title: 'ay tentación',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/b7/8d/c1/b78dc119-162d-2751-3ca7-52a1cf0f4570/mzaf_12285129704114067415.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/ay-tentaci%C3%B3n/1475559999?i=1475560007&uo=4',
          spotify: 'https://open.spotify.com/search/Chicarica%20ay%20tentaci%C3%B3n',
          youtube:
            'https://www.youtube.com/results?search_query=Chicarica%20ay%20tentaci%C3%B3n',
        },
      },
      {
        title: 'Wepa',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Chicarica%20Wepa',
          youtube: 'https://www.youtube.com/results?search_query=Chicarica%20Wepa',
        },
      },
    ],
    artistLinks: {
      appleMusic: null,
      spotify: 'https://open.spotify.com/search/Chicarica',
      youtube: 'https://www.youtube.com/results?search_query=Chicarica',
    },
    styleDescription:
      'Set de synth pop con energía en alza, coros fáciles y un clima ideal para ver en vivo a Chicarica.',
    verdict: 'Si conectas con synth pop, este show es una parada fuerte de la jornada.',
  },
  28: {
    songs: [
      {
        title: 'BABIECA!',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/9a/24/37/9a24379e-66f8-d883-e812-62646cd012f1/mzaf_1554855076782958493.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/babieca/1804329771?i=1804329951&uo=4',
          spotify: 'https://open.spotify.com/search/Guitarricadelafuente%20BABIECA!',
          youtube:
            'https://www.youtube.com/results?search_query=Guitarricadelafuente%20BABIECA!',
        },
      },
      {
        title: 'nana triste',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Guitarricadelafuente%20nana%20triste',
          youtube:
            'https://www.youtube.com/results?search_query=Guitarricadelafuente%20nana%20triste',
        },
      },
      {
        title: 'Guantanamera',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Guitarricadelafuente%20Guantanamera',
          youtube:
            'https://www.youtube.com/results?search_query=Guitarricadelafuente%20Guantanamera',
        },
      },
    ],
    artistLinks: {
      appleMusic: null,
      spotify: 'https://open.spotify.com/search/Guitarricadelafuente',
      youtube: 'https://www.youtube.com/results?search_query=Guitarricadelafuente',
    },
    styleDescription:
      'Set de folk / flamenco pop con energía en alza, coros fáciles y un clima ideal para ver en vivo a Guitarricadelafuente.',
    verdict:
      'Si conectas con folk / flamenco pop, este show es una parada fuerte de la jornada.',
  },
  29: {
    songs: [
      {
        title: 'Hacia el Fondo',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Rubio%20Hacia%20el%20Fondo',
          youtube:
            'https://www.youtube.com/results?search_query=Rubio%20Hacia%20el%20Fondo',
        },
      },
      {
        title: 'Me Asusta Amar Tanto la Soledad',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/9c/87/22/9c872279-ec67-2109-fc8a-72e16b1f67d6/mzaf_10917630051212224469.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/me-asusta-amar-tanto-la-soledad/1866981907?i=1866982109&uo=4',
          spotify:
            'https://open.spotify.com/search/Rubio%20Me%20Asusta%20Amar%20Tanto%20la%20Soledad',
          youtube:
            'https://www.youtube.com/results?search_query=Rubio%20Me%20Asusta%20Amar%20Tanto%20la%20Soledad',
        },
      },
      {
        title: 'Mi Chica',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Rubio%20Mi%20Chica',
          youtube: 'https://www.youtube.com/results?search_query=Rubio%20Mi%20Chica',
        },
      },
    ],
    artistLinks: {
      appleMusic: null,
      spotify: 'https://open.spotify.com/search/Rubio',
      youtube: 'https://www.youtube.com/results?search_query=Rubio',
    },
    styleDescription:
      'Set de pop experimental con energía en alza, coros fáciles y un clima ideal para ver en vivo a Rubio.',
    verdict:
      'Si conectas con pop experimental, este show es una parada fuerte de la jornada.',
  },
  30: {
    songs: [
      {
        title: 'Arriba de la Pelota',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/Tomo%20Como%20Rey%20Arriba%20de%20la%20Pelota',
          youtube:
            'https://www.youtube.com/results?search_query=Tomo%20Como%20Rey%20Arriba%20de%20la%20Pelota',
        },
      },
      {
        title: 'Los Que Toman Como Rey',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/Tomo%20Como%20Rey%20Los%20Que%20Toman%20Como%20Rey',
          youtube:
            'https://www.youtube.com/results?search_query=Tomo%20Como%20Rey%20Los%20Que%20Toman%20Como%20Rey',
        },
      },
      {
        title: 'Weón',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Tomo%20Como%20Rey%20We%C3%B3n',
          youtube:
            'https://www.youtube.com/results?search_query=Tomo%20Como%20Rey%20We%C3%B3n',
        },
      },
    ],
    artistLinks: {
      appleMusic: null,
      spotify: 'https://open.spotify.com/search/Tomo%20Como%20Rey',
      youtube: 'https://www.youtube.com/results?search_query=Tomo%20Como%20Rey',
    },
    styleDescription:
      'Set de cumbia / ska con energía en alza, coros fáciles y un clima ideal para ver en vivo a Tomo Como Rey.',
    verdict:
      'Si conectas con cumbia / ska, este show es una parada fuerte de la jornada.',
  },
  31: {
    songs: [
      {
        title: 'School of Rock',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/School%20of%20Rock%20School%20of%20Rock',
          youtube:
            'https://www.youtube.com/results?search_query=School%20of%20Rock%20School%20of%20Rock',
        },
      },
      {
        title: "It's a Long Way to the Top",
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            "https://open.spotify.com/search/School%20of%20Rock%20It's%20a%20Long%20Way%20to%20the%20Top",
          youtube:
            "https://www.youtube.com/results?search_query=School%20of%20Rock%20It's%20a%20Long%20Way%20to%20the%20Top",
        },
      },
      {
        title: 'Are You Ready To Rock',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/School%20of%20Rock%20Are%20You%20Ready%20To%20Rock',
          youtube:
            'https://www.youtube.com/results?search_query=School%20of%20Rock%20Are%20You%20Ready%20To%20Rock',
        },
      },
    ],
    artistLinks: {
      appleMusic: null,
      spotify: 'https://open.spotify.com/search/School%20of%20Rock',
      youtube: 'https://www.youtube.com/results?search_query=School%20of%20Rock',
    },
    styleDescription:
      'Set de rock con energía en alza, coros fáciles y un clima ideal para ver en vivo a School of Rock.',
    verdict: 'Si conectas con rock, este show es una parada fuerte de la jornada.',
  },
  32: {
    songs: [
      {
        title: 'Wasa3 Wasa3',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Wassa%20Wassa%20Wasa3%20Wasa3',
          youtube:
            'https://www.youtube.com/results?search_query=Wassa%20Wassa%20Wasa3%20Wasa3',
        },
      },
      {
        title: 'Guasa, Guasa',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/Wassa%20Wassa%20Guasa%2C%20Guasa',
          youtube:
            'https://www.youtube.com/results?search_query=Wassa%20Wassa%20Guasa%2C%20Guasa',
        },
      },
      {
        title: 'Guasa Guasa (feat. Voltio)',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/Wassa%20Wassa%20Guasa%20Guasa%20(feat.%20Voltio)',
          youtube:
            'https://www.youtube.com/results?search_query=Wassa%20Wassa%20Guasa%20Guasa%20(feat.%20Voltio)',
        },
      },
    ],
    artistLinks: {
      appleMusic: null,
      spotify: 'https://open.spotify.com/search/Wassa%20Wassa',
      youtube: 'https://www.youtube.com/results?search_query=Wassa%20Wassa',
    },
    styleDescription:
      'Set de música africana con energía en alza, coros fáciles y un clima ideal para ver en vivo a Wassa Wassa.',
    verdict:
      'Si conectas con música africana, este show es una parada fuerte de la jornada.',
  },
  33: {
    songs: [
      {
        title: 'Objeción Denegada',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/31%20Minutos%20Objeci%C3%B3n%20Denegada',
          youtube:
            'https://www.youtube.com/results?search_query=31%20Minutos%20Objeci%C3%B3n%20Denegada',
        },
      },
      {
        title: 'Mi Equilibrio Espiritual',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify:
            'https://open.spotify.com/search/31%20Minutos%20Mi%20Equilibrio%20Espiritual',
          youtube:
            'https://www.youtube.com/results?search_query=31%20Minutos%20Mi%20Equilibrio%20Espiritual',
        },
      },
      {
        title: 'Bailan Sin Cesar',
        previewUrl: null,
        links: {
          appleMusic: null,
          spotify: 'https://open.spotify.com/search/31%20Minutos%20Bailan%20Sin%20Cesar',
          youtube:
            'https://www.youtube.com/results?search_query=31%20Minutos%20Bailan%20Sin%20Cesar',
        },
      },
    ],
    artistLinks: {
      appleMusic: null,
      spotify: 'https://open.spotify.com/search/31%20Minutos',
      youtube: 'https://www.youtube.com/results?search_query=31%20Minutos',
    },
    styleDescription:
      'Set de pop infantil / humor con energía en alza, coros fáciles y un clima ideal para ver en vivo a 31 Minutos.',
    verdict:
      'Si conectas con pop infantil / humor, este show es una parada fuerte de la jornada.',
  },
};

export const PREVIEW_FALLBACK: ArtistPreview = {
  songs: [
    {
      title: 'Busca su set en Spotify',
      previewUrl: null,
      links: {
        appleMusic: null,
        spotify: 'https://open.spotify.com/search/musica%20en%20vivo',
        youtube: 'https://www.youtube.com/results?search_query=musica+en+vivo',
      },
    },
    {
      title: 'Revisa su playlist oficial',
      previewUrl: null,
      links: {
        appleMusic: null,
        spotify: 'https://open.spotify.com/search/playlist%20oficial',
        youtube: 'https://www.youtube.com/results?search_query=playlist+oficial',
      },
    },
    {
      title: 'Escucha una sesión en vivo',
      previewUrl: null,
      links: {
        appleMusic: null,
        spotify: 'https://open.spotify.com/search/live%20session',
        youtube: 'https://www.youtube.com/results?search_query=live+session',
      },
    },
  ],
  artistLinks: {
    appleMusic: null,
    spotify: 'https://open.spotify.com/search',
    youtube: 'https://www.youtube.com/results?search_query=musica',
  },
  styleDescription:
    'No encontramos una previa específica para este artista en este momento.',
  verdict: 'Igual puede sorprender en vivo; dale una escucha rápida antes del show.',
};
