import type { ArtistPreview } from '@/features/lineup/types';

// Generated by scripts/update-artist-listening-data.mjs
// Snapshot: 2026-03-14T16:28:48.991Z
export const ARTIST_PREVIEWS: Record<number, ArtistPreview> = {
  1: {
    songs: [
      {
        title: 'Asi Yo Soy',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/a7/6e/d4/a76ed4f0-3689-0108-2beb-c43fd50abe5c/mzaf_4110829861243530862.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/asi-yo-soy/322039048?i=322039455&uo=4',
          spotify: 'https://open.spotify.com/search/Zaturno%20Asi%20Yo%20Soy',
          youtube:
            'https://www.youtube.com/results?search_query=Zaturno%20Asi%20Yo%20Soy',
        },
      },
      {
        title: 'Ven Ven',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/93/fd/ee/93fdee92-81b5-8433-f807-40a2a5956f5b/mzaf_4628617779994813319.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/ven-ven/322039048?i=322039307&uo=4',
          spotify: 'https://open.spotify.com/search/Zaturno%20Ven%20Ven',
          youtube: 'https://www.youtube.com/results?search_query=Zaturno%20Ven%20Ven',
        },
      },
      {
        title: 'Busca la Salida (feat. Nicole)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/e2/b1/88/e2b18833-439e-c661-3fd9-d66f981b2efd/mzaf_18206964235893663576.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/busca-la-salida-feat-nicole/429730209?i=429730447&uo=4',
          spotify:
            'https://open.spotify.com/search/Zaturno%20Busca%20la%20Salida%20(feat.%20Nicole)',
          youtube:
            'https://www.youtube.com/results?search_query=Zaturno%20Busca%20la%20Salida%20(feat.%20Nicole)',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music/6c/55/3a/mzi.vaptzahz.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/zaturno/322039158?uo=4',
      spotify: 'https://open.spotify.com/search/Zaturno',
      youtube: 'https://www.youtube.com/results?search_query=Zaturno',
    },
    styleDescription:
      'Zaturno es rapero chileno. Para esta guía, lo ubicamos en hip hop / rap chileno. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa hip hop / rap chileno y te calza el perfil real de Zaturno, este show es una buena opción para priorizar en la jornada.',
  },
  2: {
    songs: [
      {
        title: 'Domingo de ramos',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/41/18/6f/41186f35-262b-68f4-f2e3-237009379cbb/mzaf_8490179389649102943.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/domingo-de-ramos/1842902072?i=1842902075&uo=4',
          spotify: 'https://open.spotify.com/search/Candelabro%20Domingo%20de%20ramos',
          youtube:
            'https://www.youtube.com/results?search_query=Candelabro%20Domingo%20de%20ramos',
        },
      },
      {
        title: 'Pecado',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/27/b1/79/27b1797b-3018-7386-64c8-9723f0b8ba41/mzaf_8151309272337852009.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/pecado/1842902072?i=1842902634&uo=4',
          spotify: 'https://open.spotify.com/search/Candelabro%20Pecado',
          youtube: 'https://www.youtube.com/results?search_query=Candelabro%20Pecado',
        },
      },
      {
        title: 'Prisión de carne',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/9f/3f/8a/9f3f8a77-4d9b-6b9f-37ff-b395bb0c8233/mzaf_10671297754502004403.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/prisi%C3%B3n-de-carne/1842902072?i=1842902080&uo=4',
          spotify:
            'https://open.spotify.com/search/Candelabro%20Prisi%C3%B3n%20de%20carne',
          youtube:
            'https://www.youtube.com/results?search_query=Candelabro%20Prisi%C3%B3n%20de%20carne',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/7c/85/2c/7c852c54-3300-4ec2-79e6-bcfe8dd6b813/199538942446.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/candelabro/1723158320?uo=4',
      spotify: 'https://open.spotify.com/search/Candelabro',
      youtube: 'https://www.youtube.com/results?search_query=Candelabro',
    },
    styleDescription:
      'Candelabro aparece en MusicBrainz como banda, asociado a Chile, con etiquetas progressive rock / latin rock. Para esta guía, lo ubicamos en indie rock / rock alternativo. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa indie rock / rock alternativo y te calza el perfil real de Candelabro, este show es una buena opción para priorizar en la jornada.',
  },
  3: {
    songs: [
      {
        title: 'End of Beginning',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/6e/df/af/6edfaf58-f901-e9b5-840b-9ac9e37f34b7/mzaf_8465065510938624101.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/end-of-beginning/1632447652?i=1632448108&uo=4',
          spotify: 'https://open.spotify.com/search/Djo%20End%20of%20Beginning',
          youtube:
            'https://www.youtube.com/results?search_query=Djo%20End%20of%20Beginning',
        },
      },
      {
        title: 'Basic Being Basic',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/2d/6e/5b/2d6e5bd0-7e8b-98a4-2efd-7a1a458b18e6/mzaf_56754998493673707.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/basic-being-basic/1791184860?i=1791184865&uo=4',
          spotify: 'https://open.spotify.com/search/Djo%20Basic%20Being%20Basic',
          youtube:
            'https://www.youtube.com/results?search_query=Djo%20Basic%20Being%20Basic',
        },
      },
      {
        title: "Charlie's Garden",
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/f4/59/e0/f459e05f-2223-6377-b9dd-d2dca3ddfacf/mzaf_63436087501465436.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/charlies-garden/1791184860?i=1791184876&uo=4',
          spotify: "https://open.spotify.com/search/Djo%20Charlie's%20Garden",
          youtube:
            "https://www.youtube.com/results?search_query=Djo%20Charlie's%20Garden",
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/e5/94/31/e59431de-7591-58e6-c4d4-105b6373ad6a/5056494917336_1.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/djo/1473178582?uo=4',
      spotify: 'https://open.spotify.com/search/Djo',
      youtube: 'https://www.youtube.com/results?search_query=Djo',
    },
    styleDescription:
      'Djo aparece en MusicBrainz como artista solista, asociado a Estados Unidos, con etiquetas indie rock / indie pop. Para esta guía, lo ubicamos en indie rock / pop psicodélico. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa indie rock / pop psicodélico y te calza el perfil real de Djo, este show es una buena opción para priorizar en la jornada.',
  },
  4: {
    songs: [
      {
        title: 'BIRDS',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/15/aa/94/15aa94d1-9a61-a49e-d150-77be3fe62b88/mzaf_7075406671259860362.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/birds/1805820903?i=1805821732&uo=4',
          spotify: 'https://open.spotify.com/search/Turnstile%20BIRDS',
          youtube: 'https://www.youtube.com/results?search_query=Turnstile%20BIRDS',
        },
      },
      {
        title: 'NEVER ENOUGH',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/d3/62/d1/d362d1e9-6fc6-5dbf-f212-4e64b8d44295/mzaf_13612974613437935378.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/never-enough/1805820903?i=1805820909&uo=4',
          spotify: 'https://open.spotify.com/search/Turnstile%20NEVER%20ENOUGH',
          youtube:
            'https://www.youtube.com/results?search_query=Turnstile%20NEVER%20ENOUGH',
        },
      },
      {
        title: 'BLACKOUT',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/55/72/96/55729631-b8bb-9bb4-eed1-2ef01d77768d/mzaf_11256081667780001792.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/blackout/1576430192?i=1576430194&uo=4',
          spotify: 'https://open.spotify.com/search/Turnstile%20BLACKOUT',
          youtube: 'https://www.youtube.com/results?search_query=Turnstile%20BLACKOUT',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/d1/1c/28/d11c28a8-0e83-41c3-afc7-b873dd7be188/075679614896.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/turnstile/4472006?uo=4',
      spotify: 'https://open.spotify.com/search/Turnstile',
      youtube: 'https://www.youtube.com/results?search_query=Turnstile',
    },
    styleDescription:
      'Turnstile es grupo estadounidense de hardcore punk. Para esta guía, lo ubicamos en hardcore punk / rock alternativo. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa hardcore punk / rock alternativo y te calza el perfil real de Turnstile, este show es una buena opción para priorizar en la jornada.',
  },
  5: {
    songs: [
      {
        title: 'I Am the Grinch (feat. Fletcher Jones)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/bb/92/4b/bb924b7c-a021-1ea7-37ea-0f61abfbd2c4/mzaf_4185058720691205447.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/i-am-the-grinch-feat-fletcher-jones/1441150753?i=1441150755&uo=4',
          spotify:
            'https://open.spotify.com/search/Tyler%2C%20The%20Creator%20I%20Am%20the%20Grinch%20(feat.%20Fletcher%20Jones)',
          youtube:
            'https://www.youtube.com/results?search_query=Tyler%2C%20The%20Creator%20I%20Am%20the%20Grinch%20(feat.%20Fletcher%20Jones)',
        },
      },
      {
        title: 'Big Bag',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/a1/70/ca/a170cabf-73c2-4205-f99c-17871ab4e8fb/mzaf_16266397031078989272.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/big-bag/1441586573?i=1441586726&uo=4',
          spotify: 'https://open.spotify.com/search/Tyler%2C%20The%20Creator%20Big%20Bag',
          youtube:
            'https://www.youtube.com/results?search_query=Tyler%2C%20The%20Creator%20Big%20Bag',
        },
      },
      {
        title: 'Whoville',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/a3/2b/9f/a32b9f18-1dd7-c845-3d88-4727fce32606/mzaf_14488825162935589764.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/whoville/1441586573?i=1441586584&uo=4',
          spotify: 'https://open.spotify.com/search/Tyler%2C%20The%20Creator%20Whoville',
          youtube:
            'https://www.youtube.com/results?search_query=Tyler%2C%20The%20Creator%20Whoville',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/5b/b6/1b/5bb61b9a-f308-c5a2-97f6-8b356c81cf0a/886447423165.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/tyler-the-creator/420368335?uo=4',
      spotify: 'https://open.spotify.com/search/Tyler%2C%20The%20Creator',
      youtube: 'https://www.youtube.com/results?search_query=Tyler%2C%20The%20Creator',
    },
    styleDescription:
      'Tyler, the Creator es rapero y productor discográfico estadounidense. Para esta guía, lo ubicamos en hip hop / rap alternativo. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa hip hop / rap alternativo y te calza el perfil real de Tyler, The Creator, este show es una buena opción para priorizar en la jornada.',
  },
  6: {
    songs: [
      {
        title: 'Mejor Que Yo',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/14/df/02/14df024c-b8ca-4f9d-7d61-6e0c242bc6d4/mzaf_13670860997702536437.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/mejor-que-yo/1604456252?i=1604456255&uo=4',
          spotify: 'https://open.spotify.com/search/Astronautiko%20Mejor%20Que%20Yo',
          youtube:
            'https://www.youtube.com/results?search_query=Astronautiko%20Mejor%20Que%20Yo',
        },
      },
      {
        title: 'Sombra Negra',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/08/04/02/080402f5-c9a2-2d16-fab1-78fd3366450e/mzaf_7110741225566161195.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/sombra-negra/1671601551?i=1671601566&uo=4',
          spotify: 'https://open.spotify.com/search/Astronautiko%20Sombra%20Negra',
          youtube:
            'https://www.youtube.com/results?search_query=Astronautiko%20Sombra%20Negra',
        },
      },
      {
        title: 'Oie amor',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/15/69/e1/1569e162-adea-89c5-d32e-c6d2050a58f8/mzaf_10567410352062771096.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/oie-amor/1763328127?i=1763328413&uo=4',
          spotify: 'https://open.spotify.com/search/Astronautiko%20Oie%20amor',
          youtube:
            'https://www.youtube.com/results?search_query=Astronautiko%20Oie%20amor',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/45/27/0f/45270f97-f068-4145-b402-202b1608c686/196626208439.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/astronautiko/1512393096?uo=4',
      spotify: 'https://open.spotify.com/search/Astronautiko',
      youtube: 'https://www.youtube.com/results?search_query=Astronautiko',
    },
    styleDescription:
      'Astronautiko aparece en MusicBrainz como artista solista, con etiquetas tropical / hip hop. Para esta guía, lo ubicamos en folk urbano / rap. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa folk urbano / rap y te calza el perfil real de Astronautiko, este show es una buena opción para priorizar en la jornada.',
  },
  7: {
    songs: [
      {
        title: 'De Nada',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/65/c2/a1/65c2a100-0955-fbf5-2c42-3c7b382529d3/mzaf_18158400402842454398.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/de-nada/1653867075?i=1653867529&uo=4',
          spotify: 'https://open.spotify.com/search/Yami%20Safdie%20De%20Nada',
          youtube:
            'https://www.youtube.com/results?search_query=Yami%20Safdie%20De%20Nada',
        },
      },
      {
        title: 'Me Equivoqué',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/3a/30/b5/3a30b58f-6d2c-8b3f-6430-f12809923191/mzaf_524481580194869608.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/me-equivoqu%C3%A9/1675548222?i=1675548223&uo=4',
          spotify: 'https://open.spotify.com/search/Yami%20Safdie%20Me%20Equivoqu%C3%A9',
          youtube:
            'https://www.youtube.com/results?search_query=Yami%20Safdie%20Me%20Equivoqu%C3%A9',
        },
      },
      {
        title: 'Señales',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/ae/b5/cb/aeb5cb7b-2343-d474-be5b-c6e6eaf9c311/mzaf_14078983340062624281.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/se%C3%B1ales/1688805963?i=1688805966&uo=4',
          spotify: 'https://open.spotify.com/search/Yami%20Safdie%20Se%C3%B1ales',
          youtube:
            'https://www.youtube.com/results?search_query=Yami%20Safdie%20Se%C3%B1ales',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/e3/f3/d9/e3f3d99e-3e48-5b2c-070a-3bb6c250d87a/5054197434839.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/yami-safdie/1291593068?uo=4',
      spotify: 'https://open.spotify.com/search/Yami%20Safdie',
      youtube: 'https://www.youtube.com/results?search_query=Yami%20Safdie',
    },
    styleDescription:
      'Yami Safdie es cantante argentina. Para esta guía, lo ubicamos en pop / indie pop. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa pop / indie pop y te calza el perfil real de Yami Safdie, este show es una buena opción para priorizar en la jornada.',
  },
  8: {
    songs: [
      {
        title: 'who’s your boyfriend',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/fe/ee/24/feee244e-b2f7-d488-8b00-e6c69ef2b8d7/mzaf_570126664547596035.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/whos-your-boyfriend/1831345087?i=1831345173&uo=4',
          spotify:
            'https://open.spotify.com/search/Royel%20Otis%20who%E2%80%99s%20your%20boyfriend',
          youtube:
            'https://www.youtube.com/results?search_query=Royel%20Otis%20who%E2%80%99s%20your%20boyfriend',
        },
      },
      {
        title: 'Linger (SiriusXM Session)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/81/70/72/8170727e-5c4e-5fcc-427b-410b4b9441c6/mzaf_7008226677286998422.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/linger-siriusxm-session/1747990430?i=1747990434&uo=4',
          spotify:
            'https://open.spotify.com/search/Royel%20Otis%20Linger%20(SiriusXM%20Session)',
          youtube:
            'https://www.youtube.com/results?search_query=Royel%20Otis%20Linger%20(SiriusXM%20Session)',
        },
      },
      {
        title: 'say something',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/9b/ad/f0/9badf009-c67a-f48a-d4df-cb311bf0f6e9/mzaf_13577224377559633355.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/say-something/1820542978?i=1820543519&uo=4',
          spotify: 'https://open.spotify.com/search/Royel%20Otis%20say%20something',
          youtube:
            'https://www.youtube.com/results?search_query=Royel%20Otis%20say%20something',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/1b/bf/a2/1bbfa200-28fb-828e-479a-273f36d2eac4/25UMGIM58665.rgb.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/royel-otis/1537647213?uo=4',
      spotify: 'https://open.spotify.com/search/Royel%20Otis',
      youtube: 'https://www.youtube.com/results?search_query=Royel%20Otis',
    },
    styleDescription:
      'Royel Otis aparece en MusicBrainz como banda, con etiquetas pop / indie rock. Para esta guía, lo ubicamos en indie pop / indie rock. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa indie pop / indie rock y te calza el perfil real de Royel Otis, este show es una buena opción para priorizar en la jornada.',
  },
  9: {
    songs: [
      {
        title: 'Gabriela',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/e1/02/e6/e102e60f-e529-c7af-0a99-afadea88e0cf/mzaf_4063426124739522501.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/gabriela/1811464270?i=1811464273&uo=4',
          spotify: 'https://open.spotify.com/search/KATSEYE%20Gabriela',
          youtube: 'https://www.youtube.com/results?search_query=KATSEYE%20Gabriela',
        },
      },
      {
        title: 'Internet Girl',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/63/e3/14/63e314ce-859f-256e-fe2a-d0d0a363b3e1/mzaf_8918006845401470383.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/internet-girl/1862959660?i=1862959661&uo=4',
          spotify: 'https://open.spotify.com/search/KATSEYE%20Internet%20Girl',
          youtube:
            'https://www.youtube.com/results?search_query=KATSEYE%20Internet%20Girl',
        },
      },
      {
        title: 'Gameboy',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/b7/cb/8d/b7cb8d66-bf88-2df6-6e00-411126cba3d5/mzaf_7123490845567859253.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/gameboy/1811464270?i=1811464274&uo=4',
          spotify: 'https://open.spotify.com/search/KATSEYE%20Gameboy',
          youtube: 'https://www.youtube.com/results?search_query=KATSEYE%20Gameboy',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/ad/92/ca/ad92ca90-90f5-eb46-7a56-e7b6b88584f7/25UMGIM37394.rgb.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/katseye/1754284416?uo=4',
      spotify: 'https://open.spotify.com/search/KATSEYE',
      youtube: 'https://www.youtube.com/results?search_query=KATSEYE',
    },
    styleDescription:
      'Katseye es grupo femenino estadounidense. Para esta guía, lo ubicamos en pop. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa pop y te calza el perfil real de KATSEYE, este show es una buena opción para priorizar en la jornada.',
  },
  10: {
    songs: [
      {
        title: 'Team',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/47/e9/27/47e927ce-bf78-6a94-6a68-9ac76c69d414/mzaf_2350071649770408732.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/team/1440818584?i=1440818672&uo=4',
          spotify: 'https://open.spotify.com/search/Lorde%20Team',
          youtube: 'https://www.youtube.com/results?search_query=Lorde%20Team',
        },
      },
      {
        title: 'Ribs',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/06/37/d8/0637d80c-bc43-63fa-6bdb-ccda8412cd8e/mzaf_6914525951591873635.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/ribs/1440818584?i=1440818666&uo=4',
          spotify: 'https://open.spotify.com/search/Lorde%20Ribs',
          youtube: 'https://www.youtube.com/results?search_query=Lorde%20Ribs',
        },
      },
      {
        title: 'Royals',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/36/b5/16/36b5162c-cf3e-d8ef-eb31-5e14f2e5f616/mzaf_5021657451820310202.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/royals/1440818584?i=1440818664&uo=4',
          spotify: 'https://open.spotify.com/search/Lorde%20Royals',
          youtube: 'https://www.youtube.com/results?search_query=Lorde%20Royals',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/96/a5/09/96a50916-169b-724c-b722-b8c474406352/13UAAIM68691.rgb.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/lorde/602767352?uo=4',
      spotify: 'https://open.spotify.com/search/Lorde',
      youtube: 'https://www.youtube.com/results?search_query=Lorde',
    },
    styleDescription:
      'Lorde es cantante, compositora y productora croatoneozelandesa. Para esta guía, lo ubicamos en indie pop / electropop. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa indie pop / electropop y te calza el perfil real de Lorde, este show es una buena opción para priorizar en la jornada.',
  },
  11: {
    songs: [
      {
        title: 'Bailando Solo',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/87/81/be/8781be9d-70f5-a91d-5af4-fcd0735010d6/mzaf_5238754567565665090.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/bailando-solo/1398637829?i=1398638466&uo=4',
          spotify: 'https://open.spotify.com/search/Los%20Bunkers%20Bailando%20Solo',
          youtube:
            'https://www.youtube.com/results?search_query=Los%20Bunkers%20Bailando%20Solo',
        },
      },
      {
        title: 'Nada Nuevo Bajo el Sol',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/54/35/80/54358015-b92c-e119-e3f1-afc2ffb4e346/mzaf_1391627697210835145.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/nada-nuevo-bajo-el-sol/1445743454?i=1445743471&uo=4',
          spotify:
            'https://open.spotify.com/search/Los%20Bunkers%20Nada%20Nuevo%20Bajo%20el%20Sol',
          youtube:
            'https://www.youtube.com/results?search_query=Los%20Bunkers%20Nada%20Nuevo%20Bajo%20el%20Sol',
        },
      },
      {
        title: 'Llueve Sobre La Ciudad',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/09/28/58/09285865-246f-4472-1d08-52fa13deb1e1/mzaf_12998828905205874876.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/llueve-sobre-la-ciudad/1776311914?i=1776311924&uo=4',
          spotify:
            'https://open.spotify.com/search/Los%20Bunkers%20Llueve%20Sobre%20La%20Ciudad',
          youtube:
            'https://www.youtube.com/results?search_query=Los%20Bunkers%20Llueve%20Sobre%20La%20Ciudad',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/03/ce/46/03ce4676-1cb5-be08-fb5a-d5d019d414f9/192562626160.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/los-bunkers/41216290?uo=4',
      spotify: 'https://open.spotify.com/search/Los%20Bunkers',
      youtube: 'https://www.youtube.com/results?search_query=Los%20Bunkers',
    },
    styleDescription:
      'Los Bunkers es grupo musical de Chile. Para esta guía, lo ubicamos en rock alternativo / pop rock. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa rock alternativo / pop rock y te calza el perfil real de Los Bunkers, este show es una buena opción para priorizar en la jornada.',
  },
  12: {
    songs: [
      {
        title: 'Jefe',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview124/v4/7d/d2/b5/7dd2b531-be30-d852-fd76-c8d2c9938f37/mzaf_5902687622084564202.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/jefe/1453760785?i=1453761213&uo=4',
          spotify: 'https://open.spotify.com/search/Mano%20de%20Obra%20Jefe',
          youtube: 'https://www.youtube.com/results?search_query=Mano%20de%20Obra%20Jefe',
        },
      },
      {
        title: 'Estallar',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview114/v4/2c/cc/f8/2cccf8e7-e82d-407d-24a8-0672fcda0e82/mzaf_8855772151659913482.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/estallar/1453760785?i=1453761235&uo=4',
          spotify: 'https://open.spotify.com/search/Mano%20de%20Obra%20Estallar',
          youtube:
            'https://www.youtube.com/results?search_query=Mano%20de%20Obra%20Estallar',
        },
      },
      {
        title: 'Esfuerzo',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview114/v4/84/e0/41/84e04143-9691-c2e4-0c6d-28423c8280f8/mzaf_2657167015563705929.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/esfuerzo/1453760785?i=1453761227&uo=4',
          spotify: 'https://open.spotify.com/search/Mano%20de%20Obra%20Esfuerzo',
          youtube:
            'https://www.youtube.com/results?search_query=Mano%20de%20Obra%20Esfuerzo',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/56/9b/e5/569be5f4-e079-60f1-9abd-6a5fd20bf025/5059033318625_cover.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/mano-de-obra/1453761033?uo=4',
      spotify: 'https://open.spotify.com/search/Mano%20de%20Obra',
      youtube: 'https://www.youtube.com/results?search_query=Mano%20de%20Obra',
    },
    styleDescription:
      'Mano de Obra aparece en MusicBrainz como banda. Para esta guía, lo ubicamos en rock. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa rock y te calza el perfil real de Mano de Obra, este show es una buena opción para priorizar en la jornada.',
  },
  13: {
    songs: [
      {
        title: 'Nuestra señal',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/31/85/76/318576c0-dc77-39bd-794d-fff84b2d21aa/mzaf_1270433514114645054.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/nuestra-se%C3%B1al/1808090555?i=1808091137&uo=4',
          spotify: 'https://open.spotify.com/search/De%20Saloon%20Nuestra%20se%C3%B1al',
          youtube:
            'https://www.youtube.com/results?search_query=De%20Saloon%20Nuestra%20se%C3%B1al',
        },
      },
      {
        title: 'Te Mueres',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/75/8a/28/758a28cd-17b3-ef57-0779-3050ad62c995/mzaf_3122703559731817406.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/te-mueres/1810859606?i=1810859615&uo=4',
          spotify: 'https://open.spotify.com/search/De%20Saloon%20Te%20Mueres',
          youtube:
            'https://www.youtube.com/results?search_query=De%20Saloon%20Te%20Mueres',
        },
      },
      {
        title: 'Me Vuelves a Herir',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/54/3d/1b/543d1bff-715f-523e-e6a8-f9fb83648278/mzaf_14365833138265689195.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/me-vuelves-a-herir/1810859606?i=1810859618&uo=4',
          spotify:
            'https://open.spotify.com/search/De%20Saloon%20Me%20Vuelves%20a%20Herir',
          youtube:
            'https://www.youtube.com/results?search_query=De%20Saloon%20Me%20Vuelves%20a%20Herir',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/9f/2a/93/9f2a930b-d0d1-a526-4edc-b30cbcfba08e/199350323621.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/de-saloon/277140639?uo=4',
      spotify: 'https://open.spotify.com/search/De%20Saloon',
      youtube: 'https://www.youtube.com/results?search_query=De%20Saloon',
    },
    styleDescription:
      '«De Saloon» es una banda chilena de rock alternativo, originaria de la ciudad de Concepción. Para esta guía, lo ubicamos en pop rock / rock chileno. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa pop rock / rock chileno y te calza el perfil real de De Saloon, este show es una buena opción para priorizar en la jornada.',
  },
  14: {
    songs: [
      {
        title: 'CANIJO',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/4d/8a/34/4d8a34bc-7796-b38f-2cf3-39fbee70f7c8/mzaf_1868727725933048573.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/canijo/1690867240?i=1690867461&uo=4',
          spotify: 'https://open.spotify.com/search/Judeline%20CANIJO',
          youtube: 'https://www.youtube.com/results?search_query=Judeline%20CANIJO',
        },
      },
      {
        title: 'EN EL CIELO',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview112/v4/89/34/c4/8934c41e-2938-9a3e-402f-39cb4b616684/mzaf_13061240466176366983.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/en-el-cielo/1621114993?i=1621114999&uo=4',
          spotify: 'https://open.spotify.com/search/Judeline%20EN%20EL%20CIELO',
          youtube:
            'https://www.youtube.com/results?search_query=Judeline%20EN%20EL%20CIELO',
        },
      },
      {
        title: 'angelA',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/16/c7/2e/16c72e33-5251-7356-cffe-f1e85b1973d4/mzaf_8749393193715590095.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/angela/1774589372?i=1774589603&uo=4',
          spotify: 'https://open.spotify.com/search/Judeline%20angelA',
          youtube: 'https://www.youtube.com/results?search_query=Judeline%20angelA',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/06/22/e9/0622e916-ce72-2cc6-928c-7d490bb450a3/196922504464_Cover.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/judeline/1487503245?uo=4',
      spotify: 'https://open.spotify.com/search/Judeline',
      youtube: 'https://www.youtube.com/results?search_query=Judeline',
    },
    styleDescription:
      'Judeline es cantante española. Para esta guía, lo ubicamos en indie pop / latin pop. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa indie pop / latin pop y te calza el perfil real de Judeline, este show es una buena opción para priorizar en la jornada.',
  },
  15: {
    songs: [
      {
        title: 'Backseat',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/93/2d/78/932d7881-1564-6ba2-dfc7-19b402784e6d/mzaf_9661635533200151923.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/backseat/1815926072?i=1815926074&uo=4',
          spotify: 'https://open.spotify.com/search/Balu%20Brigada%20Backseat',
          youtube:
            'https://www.youtube.com/results?search_query=Balu%20Brigada%20Backseat',
        },
      },
      {
        title: 'So Cold',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/61/4d/77/614d77d3-882c-814e-6eaa-25c45e0af8f5/mzaf_2642987810505072254.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/so-cold/1750274324?i=1750274397&uo=4',
          spotify: 'https://open.spotify.com/search/Balu%20Brigada%20So%20Cold',
          youtube:
            'https://www.youtube.com/results?search_query=Balu%20Brigada%20So%20Cold',
        },
      },
      {
        title: 'Designer',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/eb/a9/27/eba9275c-4518-c650-60ac-5b76882f5d95/mzaf_14603606350167738896.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/designer/1690105107?i=1690105108&uo=4',
          spotify: 'https://open.spotify.com/search/Balu%20Brigada%20Designer',
          youtube:
            'https://www.youtube.com/results?search_query=Balu%20Brigada%20Designer',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/fa/f5/9b/faf59bb6-7b63-9bd2-d6ac-c48a1b7b8807/5021732812490.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/balu-brigada/1171521321?uo=4',
      spotify: 'https://open.spotify.com/search/Balu%20Brigada',
      youtube: 'https://www.youtube.com/results?search_query=Balu%20Brigada',
    },
    styleDescription:
      'Balu Brigada aparece en MusicBrainz como banda, asociado a Nueva Zelanda. Para esta guía, lo ubicamos en alt-pop / indie rock. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa alt-pop / indie rock y te calza el perfil real de Balu Brigada, este show es una buena opción para priorizar en la jornada.',
  },
  16: {
    songs: [
      {
        title: 'A Lo Cubano',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/3f/b9/3f/3fb93f23-9aec-d3fd-9009-c92e3cd31a90/mzaf_12468288675445753197.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/a-lo-cubano/726238957?i=726239001&uo=4',
          spotify: 'https://open.spotify.com/search/Orishas%20A%20Lo%20Cubano',
          youtube:
            'https://www.youtube.com/results?search_query=Orishas%20A%20Lo%20Cubano',
        },
      },
      {
        title: 'Mistica',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/49/ec/0a/49ec0a85-d065-4f05-f218-76f12f8b5b20/mzaf_13554377557023966019.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/mistica/726238957?i=726239011&uo=4',
          spotify: 'https://open.spotify.com/search/Orishas%20Mistica',
          youtube: 'https://www.youtube.com/results?search_query=Orishas%20Mistica',
        },
      },
      {
        title: '537 C U B A',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/b7/d4/76/b7d4761e-8821-5357-46c1-c261def557fa/mzaf_1983546811344994057.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/537-c-u-b-a/726238957?i=726239027&uo=4',
          spotify: 'https://open.spotify.com/search/Orishas%20537%20C%20U%20B%20A',
          youtube:
            'https://www.youtube.com/results?search_query=Orishas%20537%20C%20U%20B%20A',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music4/v4/a1/61/b1/a161b1f0-4882-82f5-017b-da8f9c8aea49/0724352141050_1500x1500_300dpi.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/orishas/103897?uo=4',
      spotify: 'https://open.spotify.com/search/Orishas',
      youtube: 'https://www.youtube.com/results?search_query=Orishas',
    },
    styleDescription:
      'Orishas es Banda cubana. Para esta guía, lo ubicamos en hip hop cubano. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa hip hop cubano y te calza el perfil real de Orishas, este show es una buena opción para priorizar en la jornada.',
  },
  17: {
    songs: [
      {
        title: 'Chica De Humo Get Funky',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview112/v4/d7/11/97/d7119789-66a4-6196-5c54-3f3888eb24f5/mzaf_1458732522473020863.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/chica-de-humo-get-funky/1659501051?i=1659501052&uo=4',
          spotify:
            'https://open.spotify.com/search/Bruno%20Borlone%20Chica%20De%20Humo%20Get%20Funky',
          youtube:
            'https://www.youtube.com/results?search_query=Bruno%20Borlone%20Chica%20De%20Humo%20Get%20Funky',
        },
      },
      {
        title: 'Mil Horas',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview112/v4/05/56/6a/05566a67-a350-13ac-01bd-b2c9ebb1bf6a/mzaf_433909434703821084.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/mil-horas/1657350518?i=1657350519&uo=4',
          spotify: 'https://open.spotify.com/search/Bruno%20Borlone%20Mil%20Horas',
          youtube:
            'https://www.youtube.com/results?search_query=Bruno%20Borlone%20Mil%20Horas',
        },
      },
      {
        title: 'La Torre de Babel Bootleg (feat. Darse)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/14/97/b2/1497b201-ac93-f481-5c43-d1def37a0305/mzaf_7545016877480964792.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/la-torre-de-babel-bootleg-feat-darse/1763707711?i=1763707720&uo=4',
          spotify:
            'https://open.spotify.com/search/Bruno%20Borlone%20La%20Torre%20de%20Babel%20Bootleg%20(feat.%20Darse)',
          youtube:
            'https://www.youtube.com/results?search_query=Bruno%20Borlone%20La%20Torre%20de%20Babel%20Bootleg%20(feat.%20Darse)',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/74/a0/b6/74a0b6e9-a8aa-45f4-31c8-86fa5021626d/7321170597750.png/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/bruno-borlone/934274543?uo=4',
      spotify: 'https://open.spotify.com/search/Bruno%20Borlone',
      youtube: 'https://www.youtube.com/results?search_query=Bruno%20Borlone',
    },
    styleDescription:
      'Bruno Borlone aparece en MusicBrainz como artista solista. Para esta guía, lo ubicamos en electrónica / dj set. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa electrónica / dj set y te calza el perfil real de Bruno Borlone, este show es una buena opción para priorizar en la jornada.',
  },
  18: {
    songs: [
      {
        title: 'Pal Casino',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview122/v4/69/3f/cf/693fcf23-8ad1-046a-5402-7f059df77581/mzaf_4719366246548021136.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/pal-casino/1627342264?i=1627342357&uo=4',
          spotify: 'https://open.spotify.com/search/Marlon%20Breeze%20Pal%20Casino',
          youtube:
            'https://www.youtube.com/results?search_query=Marlon%20Breeze%20Pal%20Casino',
        },
      },
      {
        title: 'High Von',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/ae/f0/21/aef02196-e2f3-729a-7dfe-946612f9345c/mzaf_15987079451536679046.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/high-von/1702604430?i=1702604627&uo=4',
          spotify: 'https://open.spotify.com/search/Marlon%20Breeze%20High%20Von',
          youtube:
            'https://www.youtube.com/results?search_query=Marlon%20Breeze%20High%20Von',
        },
      },
      {
        title: 'De mecha en el meche',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/e8/5c/cf/e85ccf69-d8e8-7437-442e-3b353712e897/mzaf_4630968234853409912.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/de-mecha-en-el-meche/1702604430?i=1702604435&uo=4',
          spotify:
            'https://open.spotify.com/search/Marlon%20Breeze%20De%20mecha%20en%20el%20meche',
          youtube:
            'https://www.youtube.com/results?search_query=Marlon%20Breeze%20De%20mecha%20en%20el%20meche',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/08/b4/fc/08b4fc0c-39cb-b901-fd39-c1375b57f73f/0.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/marlon-breeze/1017950967?uo=4',
      spotify: 'https://open.spotify.com/search/Marlon%20Breeze',
      youtube: 'https://www.youtube.com/results?search_query=Marlon%20Breeze',
    },
    styleDescription:
      'Marlon Breeze aparece en MusicBrainz como artista solista. Para esta guía, lo ubicamos en trap / hip hop. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa trap / hip hop y te calza el perfil real de Marlon Breeze, este show es una buena opción para priorizar en la jornada.',
  },
  19: {
    songs: [
      {
        title: 'Fly',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/14/f8/4e/14f84eea-4d6e-6ff8-264e-f871fa4ca8a7/mzaf_15347054947694272825.plus.aac.p.m4a',
        links: {
          appleMusic: 'https://music.apple.com/cl/album/fly/1689034600?i=1689034601&uo=4',
          spotify: 'https://open.spotify.com/search/Aura%20Bae%20Fly',
          youtube: 'https://www.youtube.com/results?search_query=Aura%20Bae%20Fly',
        },
      },
      {
        title: 'High',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview122/v4/e5/14/37/e5143776-b852-cd90-f6da-3aa4d3a91209/mzaf_9417616443338049222.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/high/1642796187?i=1642796189&uo=4',
          spotify: 'https://open.spotify.com/search/Aura%20Bae%20High',
          youtube: 'https://www.youtube.com/results?search_query=Aura%20Bae%20High',
        },
      },
      {
        title: 'Unu',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview112/v4/e1/6a/c3/e16ac3a3-b152-3368-432b-8bb8da09d77e/mzaf_12342271302052773132.plus.aac.p.m4a',
        links: {
          appleMusic: 'https://music.apple.com/cl/album/unu/1642795969?i=1642795970&uo=4',
          spotify: 'https://open.spotify.com/search/Aura%20Bae%20Unu',
          youtube: 'https://www.youtube.com/results?search_query=Aura%20Bae%20Unu',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/d9/56/6b/d9566b7c-25f4-1302-04ff-934466d7b80b/0.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/aura-bae/1572198218?uo=4',
      spotify: 'https://open.spotify.com/search/Aura%20Bae',
      youtube: 'https://www.youtube.com/results?search_query=Aura%20Bae',
    },
    styleDescription:
      'Aura Bae aparece en MusicBrainz como artista solista. Para esta guía, lo ubicamos en urbano. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa urbano y te calza el perfil real de Aura Bae, este show es una buena opción para priorizar en la jornada.',
  },
  20: {
    songs: [
      {
        title: 'Febrero',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/66/54/e8/6654e844-5c17-3861-9f62-ebe9c92639df/mzaf_16945377401958583435.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/febrero/1673897956?i=1673897958&uo=4',
          spotify: 'https://open.spotify.com/search/Katteyes%20Febrero',
          youtube: 'https://www.youtube.com/results?search_query=Katteyes%20Febrero',
        },
      },
      {
        title: 'jukiada',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/5c/08/85/5c0885e9-4b77-02f1-0ff7-ce5b78189929/mzaf_17323876680133083884.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/jukiada/1702795438?i=1702795441&uo=4',
          spotify: 'https://open.spotify.com/search/Katteyes%20jukiada',
          youtube: 'https://www.youtube.com/results?search_query=Katteyes%20jukiada',
        },
      },
      {
        title: 'TODO KE VER',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/11/1d/7b/111d7b97-9892-6f81-39f9-89fd322cc50e/mzaf_16985197681039504625.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/todo-ke-ver/1831112143?i=1831112149&uo=4',
          spotify: 'https://open.spotify.com/search/Katteyes%20TODO%20KE%20VER',
          youtube:
            'https://www.youtube.com/results?search_query=Katteyes%20TODO%20KE%20VER',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/02/82/2b/02822be3-b774-a15e-bc10-f18a4e88e483/197188254230.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/katteyes/1648818255?uo=4',
      spotify: 'https://open.spotify.com/search/Katteyes',
      youtube: 'https://www.youtube.com/results?search_query=Katteyes',
    },
    styleDescription:
      'Katteyes aparece en MusicBrainz como artista solista, asociado a Chile. Para esta guía, lo ubicamos en electrónica / dance. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa electrónica / dance y te calza el perfil real de Katteyes, este show es una buena opción para priorizar en la jornada.',
  },
  21: {
    songs: [
      {
        title: 'Me Rehúso',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/12/0f/4e/120f4eaf-919e-2e6b-94cc-470698a8c68b/mzaf_17810599070886904293.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/me-reh%C3%BAso/1248528194?i=1248528301&uo=4',
          spotify: 'https://open.spotify.com/search/Aerobica%20Me%20Reh%C3%BAso',
          youtube:
            'https://www.youtube.com/results?search_query=Aerobica%20Me%20Reh%C3%BAso',
        },
      },
      {
        title: 'PROVENZA',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/1e/f7/a9/1ef7a9a5-5a4c-79c3-7261-385757ad26dc/mzaf_5089172852372346456.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/china-feat-j-balvin-ozuna/1473307002?i=1473307010&uo=4',
          spotify: 'https://open.spotify.com/search/Aerobica%20PROVENZA',
          youtube: 'https://www.youtube.com/results?search_query=Aerobica%20PROVENZA',
        },
      },
      {
        title: 'Cold Heart (PNAU Remix)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/e8/d4/c4/e8d4c4f0-35c7-d5c2-76d5-ea5d2cacff32/mzaf_3672914764309637319.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/cold-heart-pnau-remix/1578986656?i=1578986673&uo=4',
          spotify:
            'https://open.spotify.com/search/Aerobica%20Cold%20Heart%20(PNAU%20Remix)',
          youtube:
            'https://www.youtube.com/results?search_query=Aerobica%20Cold%20Heart%20(PNAU%20Remix)',
        },
      },
    ],
    artistImageUrl:
      'https://cdn-images.dzcdn.net/images/artist/0f70b114760878b066499b598d5a03cd/1000x1000-000000-80-0-0.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/aerobica/1574333784?uo=4',
      spotify: 'https://open.spotify.com/search/Aerobica',
      youtube: 'https://www.youtube.com/results?search_query=Aerobica',
    },
    styleDescription:
      'Aerobica aparece en MusicBrainz como banda. Para esta guía, lo ubicamos en house. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa house y te calza el perfil real de Aerobica, este show es una buena opción para priorizar en la jornada.',
  },
  22: {
    songs: [
      {
        title: 'Heridas',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview113/v4/58/05/08/580508c6-8753-874c-d5b4-f37a14f50d28/mzaf_5895898778393030001.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/heridas/1666391370?i=1666391371&uo=4',
          spotify: 'https://open.spotify.com/search/R%C3%98Z%20Heridas',
          youtube: 'https://www.youtube.com/results?search_query=R%C3%98Z%20Heridas',
        },
      },
      {
        title: 'weeknd<3 (edit)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/54/9b/50/549b50b2-096b-78b4-a41c-5de271ae90e5/mzaf_14301302605890819206.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/weeknd-3-edit/1707564621?i=1707564622&uo=4',
          spotify: 'https://open.spotify.com/search/R%C3%98Z%20weeknd%3C3%20(edit)',
          youtube:
            'https://www.youtube.com/results?search_query=R%C3%98Z%20weeknd%3C3%20(edit)',
        },
      },
      {
        title: 'Out of Sight',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview112/v4/3f/38/bd/3f38bdc4-a073-91ac-3111-bfa2ceb68e4b/mzaf_12275784910563259601.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/out-of-sight/1643352082?i=1643352083&uo=4',
          spotify: 'https://open.spotify.com/search/R%C3%98Z%20Out%20of%20Sight',
          youtube:
            'https://www.youtube.com/results?search_query=R%C3%98Z%20Out%20of%20Sight',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music123/v4/86/8f/0d/868f0dd6-e75f-b089-c169-73be6bd31e60/0.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/r%C3%B8z/1497371365?uo=4',
      spotify: 'https://open.spotify.com/search/R%C3%98Z',
      youtube: 'https://www.youtube.com/results?search_query=R%C3%98Z',
    },
    styleDescription:
      'RØZ aparece en MusicBrainz como banda, asociado a México, con etiquetas dance / pop. Para esta guía, lo ubicamos en electrónica. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa electrónica y te calza el perfil real de RØZ, este show es una buena opción para priorizar en la jornada.',
  },
  23: {
    songs: [
      {
        title: 'KULIKITAKA (Locked Club Remix) [Mixed]',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/fa/0d/4c/fa0d4cdd-1eb4-b024-767f-d10ce219ba67/mzaf_10559511636820321110.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/kulikitaka-locked-club-remix-mixed/1830361185?i=1830361342&uo=4',
          spotify:
            'https://open.spotify.com/search/%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20KULIKITAKA%20(Locked%20Club%20Remix)%20%5BMixed%5D',
          youtube:
            'https://www.youtube.com/results?search_query=%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20KULIKITAKA%20(Locked%20Club%20Remix)%20%5BMixed%5D',
        },
      },
      {
        title: 'Firestarter (Empirion Mix) [Mixed]',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/35/43/00/35430020-052d-94d9-8047-8409a2a93c79/mzaf_1858862438642593966.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/firestarter-empirion-mix-mixed/1830361185?i=1830361341&uo=4',
          spotify:
            'https://open.spotify.com/search/%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20Firestarter%20(Empirion%20Mix)%20%5BMixed%5D',
          youtube:
            'https://www.youtube.com/results?search_query=%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20Firestarter%20(Empirion%20Mix)%20%5BMixed%5D',
        },
      },
      {
        title: 'ID (from Boiler Room: ¥ØU$UK€ ¥UK1MAT$U in Tokyo, Nov 9, 2024) [Mixed]',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/47/d1/12/47d112fe-06d6-85c8-ca5f-52aef4c48fb5/mzaf_2126486577152029158.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/id-from-boiler-room-%C2%A5%C3%B8u%24uk%E2%82%AC-%C2%A5uk1mat%24u-in-tokyo-nov/1830361185?i=1830361349&uo=4',
          spotify:
            'https://open.spotify.com/search/%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20ID%20(from%20Boiler%20Room%3A%20%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20in%20Tokyo%2C%20Nov%209%2C%202024)%20%5BMixed%5D',
          youtube:
            'https://www.youtube.com/results?search_query=%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20ID%20(from%20Boiler%20Room%3A%20%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U%20in%20Tokyo%2C%20Nov%209%2C%202024)%20%5BMixed%5D',
        },
      },
    ],
    artistImageUrl: null,
    artistLinks: {
      appleMusic:
        'https://music.apple.com/cl/artist/%C2%A5%C3%B8u%24uk%E2%82%AC-%C2%A5uk1mat%24u/1830360631?uo=4',
      spotify:
        'https://open.spotify.com/search/%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U',
      youtube:
        'https://www.youtube.com/results?search_query=%C2%A5%C3%98U%24UK%E2%82%AC%20%C2%A5UK1MAT%24U',
    },
    styleDescription:
      '¥ØU$UK€ ¥UK1MAT$U aparece en MusicBrainz como artista solista. Para esta guía, lo ubicamos en techno experimental. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa techno experimental y te calza el perfil real de ¥ØU$UK€ ¥UK1MAT$U, este show es una buena opción para priorizar en la jornada.',
  },
  24: {
    songs: [
      {
        title: '(It Goes Like) Nanana (Edit)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/23/d9/32/23d93263-a2d6-0ae3-6d41-ce801f4e7900/mzaf_6378555746646043520.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/it-goes-like-nanana-edit/1689088940?i=1689088958&uo=4',
          spotify:
            'https://open.spotify.com/search/Peggy%20Gou%20(It%20Goes%20Like)%20Nanana%20(Edit)',
          youtube:
            'https://www.youtube.com/results?search_query=Peggy%20Gou%20(It%20Goes%20Like)%20Nanana%20(Edit)',
        },
      },
      {
        title: 'Starry Night',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/b2/e2/82/b2e282a3-b938-0187-1d18-fd458d596b00/mzaf_6981740387405314728.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/starry-night/1678111472?i=1678111485&uo=4',
          spotify: 'https://open.spotify.com/search/Peggy%20Gou%20Starry%20Night',
          youtube:
            'https://www.youtube.com/results?search_query=Peggy%20Gou%20Starry%20Night',
        },
      },
      {
        title: 'I Go (Edit)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/11/c5/b0/11c5b00d-50c5-ff38-99e3-d32b1a40b84a/mzaf_6882863268636313645.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/i-go-edit/1677880061?i=1677880463&uo=4',
          spotify: 'https://open.spotify.com/search/Peggy%20Gou%20I%20Go%20(Edit)',
          youtube:
            'https://www.youtube.com/results?search_query=Peggy%20Gou%20I%20Go%20(Edit)',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/29/f6/3b/29f63b48-7297-934e-4ae4-c8c279412c33/191404137420.png/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/peggy-gou/1068912248?uo=4',
      spotify: 'https://open.spotify.com/search/Peggy%20Gou',
      youtube: 'https://www.youtube.com/results?search_query=Peggy%20Gou',
    },
    styleDescription:
      'Peggy Gou es DJ y productora musical surcoreana. Para esta guía, lo ubicamos en house / techno. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa house / techno y te calza el perfil real de Peggy Gou, este show es una buena opción para priorizar en la jornada.',
  },
  25: {
    songs: [
      {
        title: 'Findesemana',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/65/10/d4/6510d4d3-95ad-6e1e-1d24-f149ba984cb8/mzaf_10604986020397981861.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/findesemana/1606337284?i=1606337385&uo=4',
          spotify: 'https://open.spotify.com/search/Fonosida%20Findesemana',
          youtube: 'https://www.youtube.com/results?search_query=Fonosida%20Findesemana',
        },
      },
      {
        title: 'Hagamos Como Si Nada de Esto Hubiera Pasado (Emm Ok)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview112/v4/c6/33/1e/c6331e55-4dfc-998a-13d8-c6c986a2c241/mzaf_5748373917669096474.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/hagamos-como-si-nada-de-esto-hubiera-pasado-emm-ok/1649728014?i=1649728466&uo=4',
          spotify:
            'https://open.spotify.com/search/Fonosida%20Hagamos%20Como%20Si%20Nada%20de%20Esto%20Hubiera%20Pasado%20(Emm%20Ok)',
          youtube:
            'https://www.youtube.com/results?search_query=Fonosida%20Hagamos%20Como%20Si%20Nada%20de%20Esto%20Hubiera%20Pasado%20(Emm%20Ok)',
        },
      },
      {
        title: 'Laberinto',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/28/c4/53/28c453e1-81a7-b3a1-606a-1a992a83491e/mzaf_1919565471049278666.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/laberinto/1606337284?i=1606337393&uo=4',
          spotify: 'https://open.spotify.com/search/Fonosida%20Laberinto',
          youtube: 'https://www.youtube.com/results?search_query=Fonosida%20Laberinto',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/b8/2a/c2/b82ac21f-d757-d2bf-6bdf-c31c91144311/d1792198-ab05-4989-8fc7-06686c4c68c5.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/fonosida/1442514323?uo=4',
      spotify: 'https://open.spotify.com/search/Fonosida',
      youtube: 'https://www.youtube.com/results?search_query=Fonosida',
    },
    styleDescription:
      'Fonosida aparece en MusicBrainz como banda. Para esta guía, lo ubicamos en indie pop. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa indie pop y te calza el perfil real de Fonosida, este show es una buena opción para priorizar en la jornada.',
  },
  26: {
    songs: [
      {
        title: 'En busca de un nuevo sueño',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/14/58/d7/1458d7d9-4d47-e179-2938-edbfac714b5c/mzaf_2102349038715988942.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/en-busca-de-un-nuevo-sue%C3%B1o/1772082485?i=1772082491&uo=4',
          spotify:
            'https://open.spotify.com/search/Como%20Asesinar%20a%20Felipes%20En%20busca%20de%20un%20nuevo%20sue%C3%B1o',
          youtube:
            'https://www.youtube.com/results?search_query=Como%20Asesinar%20a%20Felipes%20En%20busca%20de%20un%20nuevo%20sue%C3%B1o',
        },
      },
      {
        title: 'Formo parte de un engaño',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/ad/37/50/ad3750ca-7ff4-6614-eed1-fcc7a7eb54f5/mzaf_285692918383078080.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/formo-parte-de-un-enga%C3%B1o/1772082485?i=1772082490&uo=4',
          spotify:
            'https://open.spotify.com/search/Como%20Asesinar%20a%20Felipes%20Formo%20parte%20de%20un%20enga%C3%B1o',
          youtube:
            'https://www.youtube.com/results?search_query=Como%20Asesinar%20a%20Felipes%20Formo%20parte%20de%20un%20enga%C3%B1o',
        },
      },
      {
        title: 'Influencia',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/66/74/7f/66747fe2-b17e-bd92-1a60-e7328dd8daa3/mzaf_4459275136608513996.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/influencia/1772082485?i=1772082999&uo=4',
          spotify:
            'https://open.spotify.com/search/Como%20Asesinar%20a%20Felipes%20Influencia',
          youtube:
            'https://www.youtube.com/results?search_query=Como%20Asesinar%20a%20Felipes%20Influencia',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/2e/01/5c/2e015c37-aa1b-dc1d-074b-2a6ec5d10c44/8447053220665.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic:
        'https://music.apple.com/cl/artist/como-asesinar-a-felipes/286954831?uo=4',
      spotify: 'https://open.spotify.com/search/Como%20Asesinar%20a%20Felipes',
      youtube:
        'https://www.youtube.com/results?search_query=Como%20Asesinar%20a%20Felipes',
    },
    styleDescription:
      'Cómo asesinar a Felipes es banda chilena de hip hop alternativo. Para esta guía, lo ubicamos en jazz rap. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa jazz rap y te calza el perfil real de Como Asesinar a Felipes, este show es una buena opción para priorizar en la jornada.',
  },
  27: {
    songs: [
      {
        title: 'Papayas',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/e2/4f/27/e24f27dc-ba14-7e27-6e58-56878f084701/mzaf_9506959644271444953.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/papayas/1190169944?i=1190169964&uo=4',
          spotify: 'https://open.spotify.com/search/Chicarica%20Papayas',
          youtube: 'https://www.youtube.com/results?search_query=Chicarica%20Papayas',
        },
      },
      {
        title: 'Té',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/c9/72/45/c9724595-e844-db7d-026d-79bfaf91097e/mzaf_4510963669043400043.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/t%C3%A9/1131496481?i=1131496502&uo=4',
          spotify: 'https://open.spotify.com/search/Chicarica%20T%C3%A9',
          youtube: 'https://www.youtube.com/results?search_query=Chicarica%20T%C3%A9',
        },
      },
      {
        title: 'Dale Mami',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/0d/1c/39/0d1c3929-b37a-418a-8a53-a6e5b6046874/mzaf_17221671354590820676.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/dale-mami/1389913281?i=1389913534&uo=4',
          spotify: 'https://open.spotify.com/search/Chicarica%20Dale%20Mami',
          youtube: 'https://www.youtube.com/results?search_query=Chicarica%20Dale%20Mami',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/41/ea/74/41ea74bd-56f9-cf87-f553-955a40e9bcf3/artwork.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/chicarica/1131496499?uo=4',
      spotify: 'https://open.spotify.com/search/Chicarica',
      youtube: 'https://www.youtube.com/results?search_query=Chicarica',
    },
    styleDescription:
      'Chicarica aparece en MusicBrainz como banda, asociado a Chile, con etiquetas downtempo / indietronica. Para esta guía, lo ubicamos en synth pop. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa synth pop y te calza el perfil real de Chicarica, este show es una buena opción para priorizar en la jornada.',
  },
  28: {
    songs: [
      {
        title: 'Guantanamera',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/92/5a/89/925a8984-8a73-94dd-46ff-064e8403b69a/mzaf_15372031237320568442.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/guantanamera/1753062808?i=1753062818&uo=4',
          spotify: 'https://open.spotify.com/search/Guitarricadelafuente%20Guantanamera',
          youtube:
            'https://www.youtube.com/results?search_query=Guitarricadelafuente%20Guantanamera',
        },
      },
      {
        title: 'Conticinio',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/72/ad/17/72ad17fa-c089-d513-a31a-3fe44e615536/mzaf_5655024349851451160.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/conticinio/1753062188?i=1753062687&uo=4',
          spotify: 'https://open.spotify.com/search/Guitarricadelafuente%20Conticinio',
          youtube:
            'https://www.youtube.com/results?search_query=Guitarricadelafuente%20Conticinio',
        },
      },
      {
        title: 'Abc',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/70/fe/37/70fe376a-32c7-5045-7f7c-f264c57eb199/mzaf_7458558741302232650.plus.aac.p.m4a',
        links: {
          appleMusic: 'https://music.apple.com/cl/album/abc/1753062737?i=1753062866&uo=4',
          spotify: 'https://open.spotify.com/search/Guitarricadelafuente%20Abc',
          youtube:
            'https://www.youtube.com/results?search_query=Guitarricadelafuente%20Abc',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/8a/c7/2c/8ac72cef-e23a-77a8-4e5e-219d3c85184d/198588162101.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic:
        'https://music.apple.com/cl/artist/guitarricadelafuente/1438242777?uo=4',
      spotify: 'https://open.spotify.com/search/Guitarricadelafuente',
      youtube: 'https://www.youtube.com/results?search_query=Guitarricadelafuente',
    },
    styleDescription:
      'Guitarricadelafuente es cantautor, compositor y músico español. Para esta guía, lo ubicamos en folk / flamenco pop. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa folk / flamenco pop y te calza el perfil real de Guitarricadelafuente, este show es una buena opción para priorizar en la jornada.',
  },
  29: {
    songs: [
      {
        title: 'Mi Chica',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/46/29/6c/46296cc0-7af1-ba9f-2372-8080acc6ba79/mzaf_1591583051208098784.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/mi-chica/1867215821?i=1867216375&uo=4',
          spotify: 'https://open.spotify.com/search/Rubio%20Mi%20Chica',
          youtube: 'https://www.youtube.com/results?search_query=Rubio%20Mi%20Chica',
        },
      },
      {
        title: 'Hacia el Fondo',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/2b/26/d0/2b26d02b-a5b4-cf9b-82aa-324dd48d5419/mzaf_11996467918758046992.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/hacia-el-fondo/1588294746?i=1588294757&uo=4',
          spotify: 'https://open.spotify.com/search/Rubio%20Hacia%20el%20Fondo',
          youtube:
            'https://www.youtube.com/results?search_query=Rubio%20Hacia%20el%20Fondo',
        },
      },
      {
        title: 'IR',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/29/80/f6/2980f6c1-1b7a-5ee4-f356-0cd5a35d57fd/mzaf_651658694956179529.plus.aac.p.m4a',
        links: {
          appleMusic: 'https://music.apple.com/cl/album/ir/1588307126?i=1588307571&uo=4',
          spotify: 'https://open.spotify.com/search/Rubio%20IR',
          youtube: 'https://www.youtube.com/results?search_query=Rubio%20IR',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/cd/f3/ff/cdf3fffe-e713-1003-624e-324363e7c729/199806862049.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/rubio/34747724?uo=4',
      spotify: 'https://open.spotify.com/search/Rubio',
      youtube: 'https://www.youtube.com/results?search_query=Rubio',
    },
    styleDescription:
      'Rubio aparece en MusicBrainz como artista solista. Para esta guía, lo ubicamos en pop experimental. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa pop experimental y te calza el perfil real de Rubio, este show es una buena opción para priorizar en la jornada.',
  },
  30: {
    songs: [
      {
        title: 'Arriba de la Pelota',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/84/6b/77/846b7774-f3ac-401c-84ef-d4f7c8dee232/mzaf_4789111228920384883.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/arriba-de-la-pelota/1804699778?i=1804700073&uo=4',
          spotify:
            'https://open.spotify.com/search/Tomo%20Como%20Rey%20Arriba%20de%20la%20Pelota',
          youtube:
            'https://www.youtube.com/results?search_query=Tomo%20Como%20Rey%20Arriba%20de%20la%20Pelota',
        },
      },
      {
        title: 'Los Que Toman Como Rey',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/a7/28/92/a728924a-94ee-2e88-1b8e-9812d259762e/mzaf_15993082385926056095.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/los-que-toman-como-rey/1804699778?i=1804699780&uo=4',
          spotify:
            'https://open.spotify.com/search/Tomo%20Como%20Rey%20Los%20Que%20Toman%20Como%20Rey',
          youtube:
            'https://www.youtube.com/results?search_query=Tomo%20Como%20Rey%20Los%20Que%20Toman%20Como%20Rey',
        },
      },
      {
        title: 'El Niño Maravilla',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/4a/03/8a/4a038aeb-0673-7df7-c089-1469a309b19e/mzaf_14377969532284826369.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/el-ni%C3%B1o-maravilla/1804699778?i=1804700249&uo=4',
          spotify:
            'https://open.spotify.com/search/Tomo%20Como%20Rey%20El%20Ni%C3%B1o%20Maravilla',
          youtube:
            'https://www.youtube.com/results?search_query=Tomo%20Como%20Rey%20El%20Ni%C3%B1o%20Maravilla',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/01/54/b3/0154b349-e3b6-55b2-e29f-b56224fbc456/199066123331.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/tomo-como-rey/167808482?uo=4',
      spotify: 'https://open.spotify.com/search/Tomo%20Como%20Rey',
      youtube: 'https://www.youtube.com/results?search_query=Tomo%20Como%20Rey',
    },
    styleDescription:
      'Tomo Como Rey aparece en MusicBrainz como banda, con etiquetas cumbia. Para esta guía, lo ubicamos en cumbia / ska. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa cumbia / ska y te calza el perfil real de Tomo Como Rey, este show es una buena opción para priorizar en la jornada.',
  },
  31: {
    songs: [
      {
        title: 'School of Rock',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/64/06/d3/6406d387-4461-adc6-8690-c62ffe04dad4/mzaf_18120629186495848421.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/school-of-rock/1749374297?i=1749374432&uo=4',
          spotify:
            'https://open.spotify.com/search/School%20of%20Rock%20School%20of%20Rock',
          youtube:
            'https://www.youtube.com/results?search_query=School%20of%20Rock%20School%20of%20Rock',
        },
      },
      {
        title: 'Stick It to the Man',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/a0/7a/c3/a07ac379-bdd4-a01c-791b-cd40adedb9af/mzaf_11558569441603492088.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/stick-it-to-the-man/1056441943?i=1056442619&uo=4',
          spotify:
            'https://open.spotify.com/search/School%20of%20Rock%20Stick%20It%20to%20the%20Man',
          youtube:
            'https://www.youtube.com/results?search_query=School%20of%20Rock%20Stick%20It%20to%20the%20Man',
        },
      },
      {
        title: 'Finale',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/3b/a2/92/3ba29287-4dfc-80e2-939a-eac4f1e52e58/mzaf_3249206590151468382.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/finale/1056441943?i=1056442626&uo=4',
          spotify: 'https://open.spotify.com/search/School%20of%20Rock%20Finale',
          youtube:
            'https://www.youtube.com/results?search_query=School%20of%20Rock%20Finale',
        },
      },
    ],
    artistImageUrl:
      'https://r2.theaudiodb.com/images/media/artist/thumb/swuyrq1432757155.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/school-of-rock/1506507844?uo=4',
      spotify: 'https://open.spotify.com/search/School%20of%20Rock',
      youtube: 'https://www.youtube.com/results?search_query=School%20of%20Rock',
    },
    styleDescription:
      'School of Rock es un musical basado en la película homónima de 2003, con libreto de Julian Fellowes, música de Andrew Lloyd Webber y letras de Glenn Slater. Para esta guía, lo ubicamos en rock. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa rock y te calza el perfil real de School of Rock, este show es una buena opción para priorizar en la jornada.',
  },
  32: {
    songs: [
      {
        title: 'Wassa',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview122/v4/81/5e/84/815e844a-712c-a887-c389-75d3f4f96bcc/mzaf_8007243181054786553.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/wassa/1731473474?i=1731473784&uo=4',
          spotify: 'https://open.spotify.com/search/Wassa%20Wassa%20Wassa',
          youtube: 'https://www.youtube.com/results?search_query=Wassa%20Wassa%20Wassa',
        },
      },
      {
        title: 'Tatami faré',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/Music/7f/38/2f/mzm.vqbgaawf.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/tatami-far%C3%A9/151398045?i=151398063&uo=4',
          spotify: 'https://open.spotify.com/search/Wassa%20Wassa%20Tatami%20far%C3%A9',
          youtube:
            'https://www.youtube.com/results?search_query=Wassa%20Wassa%20Tatami%20far%C3%A9',
        },
      },
      {
        title: 'Borhomasi faré',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/Music/dd/4a/cd/mzm.dhosqriy.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/borhomasi-far%C3%A9/151398045?i=151398066&uo=4',
          spotify:
            'https://open.spotify.com/search/Wassa%20Wassa%20Borhomasi%20far%C3%A9',
          youtube:
            'https://www.youtube.com/results?search_query=Wassa%20Wassa%20Borhomasi%20far%C3%A9',
        },
      },
    ],
    artistImageUrl: null,
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/wassa/151398060?uo=4',
      spotify: 'https://open.spotify.com/search/Wassa%20Wassa',
      youtube: 'https://www.youtube.com/results?search_query=Wassa%20Wassa',
    },
    styleDescription:
      'Wassa Wassa aparece en MusicBrainz como banda. Para esta guía, lo ubicamos en música africana. Fuente: MusicBrainz.',
    verdict:
      'Si te interesa música africana y te calza el perfil real de Wassa Wassa, este show es una buena opción para priorizar en la jornada.',
  },
  33: {
    songs: [
      {
        title: 'Mi Equilibrio Espiritual (feat. Freddy Turbina)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/8d/95/61/8d9561f8-f963-9519-b0c3-866f48067aac/mzaf_8879995116756568973.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/mi-equilibrio-espiritual-feat-freddy-turbina/1687546227?i=1687546675&uo=4',
          spotify:
            'https://open.spotify.com/search/31%20Minutos%20Mi%20Equilibrio%20Espiritual%20(feat.%20Freddy%20Turbina)',
          youtube:
            'https://www.youtube.com/results?search_query=31%20Minutos%20Mi%20Equilibrio%20Espiritual%20(feat.%20Freddy%20Turbina)',
        },
      },
      {
        title: 'Arwrarwrirwrarwro',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/68/5e/2c/685e2cd2-b58c-9fd0-c1a1-70840acb3893/mzaf_2507668729810082257.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/arwrarwrirwrarwro/1682187343?i=1682187676&uo=4',
          spotify: 'https://open.spotify.com/search/31%20Minutos%20Arwrarwrirwrarwro',
          youtube:
            'https://www.youtube.com/results?search_query=31%20Minutos%20Arwrarwrirwrarwro',
        },
      },
      {
        title:
          'Bailan Sin Cesar (feat. Latidos Latinos Unidos Emergentes Hip-Hop Hermanos Brothers)',
        previewUrl:
          'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/a2/dc/b6/a2dcb665-8e31-df6d-5e9a-0d2e2a3225d4/mzaf_17017079500021610903.plus.aac.p.m4a',
        links: {
          appleMusic:
            'https://music.apple.com/cl/album/bailan-sin-cesar-feat-latidos-latinos-unidos-emergentes/1687546227?i=1687546239&uo=4',
          spotify:
            'https://open.spotify.com/search/31%20Minutos%20Bailan%20Sin%20Cesar%20(feat.%20Latidos%20Latinos%20Unidos%20Emergentes%20Hip-Hop%20Hermanos%20Brothers)',
          youtube:
            'https://www.youtube.com/results?search_query=31%20Minutos%20Bailan%20Sin%20Cesar%20(feat.%20Latidos%20Latinos%20Unidos%20Emergentes%20Hip-Hop%20Hermanos%20Brothers)',
        },
      },
    ],
    artistImageUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/22/18/94/221894db-b1e4-2cbb-0142-08c7e9685353/23UMGIM43825.rgb.jpg/600x600bb.jpg',
    artistLinks: {
      appleMusic: 'https://music.apple.com/cl/artist/31-minutos/325008685?uo=4',
      spotify: 'https://open.spotify.com/search/31%20Minutos',
      youtube: 'https://www.youtube.com/results?search_query=31%20Minutos',
    },
    styleDescription:
      '31 minutos es serie de televisión chilena. Para esta guía, lo ubicamos en pop infantil / humor. Fuente: Wikipedia ES.',
    verdict:
      'Si te interesa pop infantil / humor y te calza el perfil real de 31 Minutos, este show es una buena opción para priorizar en la jornada.',
  },
};

export const PREVIEW_FALLBACK: ArtistPreview = {
  songs: [
    {
      title: 'Busca su set en Spotify',
      previewUrl: null,
      links: {
        appleMusic: null,
        spotify: 'https://open.spotify.com/search/musica%20en%20vivo',
        youtube: 'https://www.youtube.com/results?search_query=musica+en+vivo',
      },
    },
    {
      title: 'Revisa su playlist oficial',
      previewUrl: null,
      links: {
        appleMusic: null,
        spotify: 'https://open.spotify.com/search/playlist%20oficial',
        youtube: 'https://www.youtube.com/results?search_query=playlist+oficial',
      },
    },
    {
      title: 'Escucha una sesión en vivo',
      previewUrl: null,
      links: {
        appleMusic: null,
        spotify: 'https://open.spotify.com/search/live%20session',
        youtube: 'https://www.youtube.com/results?search_query=live+session',
      },
    },
  ],
  artistImageUrl: null,
  artistLinks: {
    appleMusic: null,
    spotify: 'https://open.spotify.com/search',
    youtube: 'https://www.youtube.com/results?search_query=musica',
  },
  styleDescription:
    'No encontramos una previa específica para este artista en este momento.',
  verdict: 'Igual puede sorprender en vivo; dale una escucha rápida antes del show.',
};
